# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dac_gui.ui'
#
# Created: Fri Nov 11 12:12:44 2016
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_DACWindow(object):
    def setupUi(self, DACWindow):
        DACWindow.setObjectName("DACWindow")
        DACWindow.resize(816, 596)
        self.centralwidget = QtGui.QWidget(DACWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 240, 150))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.formLayoutWidget.setFont(font)
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.ch0SpinBox = QtGui.QDoubleSpinBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ch0SpinBox.setFont(font)
        self.ch0SpinBox.setDecimals(4)
        self.ch0SpinBox.setMinimum(-10.0)
        self.ch0SpinBox.setMaximum(10.0)
        self.ch0SpinBox.setSingleStep(0.02)
        self.ch0SpinBox.setObjectName("ch0SpinBox")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.ch0SpinBox)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.ch1SpinBox = QtGui.QDoubleSpinBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ch1SpinBox.setFont(font)
        self.ch1SpinBox.setDecimals(4)
        self.ch1SpinBox.setMinimum(-10.0)
        self.ch1SpinBox.setMaximum(10.0)
        self.ch1SpinBox.setSingleStep(0.02)
        self.ch1SpinBox.setObjectName("ch1SpinBox")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.ch1SpinBox)
        self.label_3 = QtGui.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_3)
        self.ch2SpinBox = QtGui.QDoubleSpinBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ch2SpinBox.setFont(font)
        self.ch2SpinBox.setDecimals(4)
        self.ch2SpinBox.setMinimum(-10.0)
        self.ch2SpinBox.setMaximum(10.0)
        self.ch2SpinBox.setSingleStep(0.02)
        self.ch2SpinBox.setObjectName("ch2SpinBox")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.ch2SpinBox)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_4)
        self.ch3SpinBox = QtGui.QDoubleSpinBox(self.formLayoutWidget)
        self.ch3SpinBox.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ch3SpinBox.setFont(font)
        self.ch3SpinBox.setWrapping(False)
        self.ch3SpinBox.setFrame(True)
        self.ch3SpinBox.setDecimals(4)
        self.ch3SpinBox.setMinimum(-10.0)
        self.ch3SpinBox.setMaximum(10.0)
        self.ch3SpinBox.setSingleStep(0.02)
        self.ch3SpinBox.setObjectName("ch3SpinBox")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.ch3SpinBox)
        self.label_5 = QtGui.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.label_5)
        self.expectedCh3 = QtGui.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.expectedCh3.setFont(font)
        self.expectedCh3.setObjectName("expectedCh3")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.expectedCh3)
        self.DC_value = QtGui.QDoubleSpinBox(self.formLayoutWidget)
        self.DC_value.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.DC_value.setFont(font)
        self.DC_value.setWrapping(False)
        self.DC_value.setFrame(True)
        self.DC_value.setDecimals(4)
        self.DC_value.setMinimum(-10.0)
        self.DC_value.setMaximum(10.0)
        self.DC_value.setSingleStep(0.02)
        self.DC_value.setProperty("value", QtCore.QVariant(0.96))
        self.DC_value.setObjectName("DC_value")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.DC_value)
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(260, 10, 540, 530))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.verticalLayoutWidget.setFont(font)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.AmplitudePlot = MatplotlibWidget(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.AmplitudePlot.setFont(font)
        self.AmplitudePlot.setObjectName("AmplitudePlot")
        self.verticalLayout.addWidget(self.AmplitudePlot)
        self.PhasePlot = MatplotlibWidget(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.PhasePlot.setFont(font)
        self.PhasePlot.setObjectName("PhasePlot")
        self.verticalLayout.addWidget(self.PhasePlot)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 160, 240, 86))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.verticalLayoutWidget_2.setFont(font)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.FixVDiffMMMM = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.FixVDiffMMMM.setFont(font)
        self.FixVDiffMMMM.setObjectName("FixVDiffMMMM")
        self.verticalLayout_2.addWidget(self.FixVDiffMMMM)
        self.FixVSumMMMM = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.FixVSumMMMM.setFont(font)
        self.FixVSumMMMM.setObjectName("FixVSumMMMM")
        self.verticalLayout_2.addWidget(self.FixVSumMMMM)
        self.NoMMMM = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.NoMMMM.setFont(font)
        self.NoMMMM.setChecked(True)
        self.NoMMMM.setObjectName("NoMMMM")
        self.verticalLayout_2.addWidget(self.NoMMMM)
        self.formLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 250, 240, 118))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.formLayoutWidget_2.setFont(font)
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_6 = QtGui.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtGui.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_7)
        self.scanIntervalLength = QtGui.QDoubleSpinBox(self.formLayoutWidget_2)
        self.scanIntervalLength.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.scanIntervalLength.setFont(font)
        self.scanIntervalLength.setWrapping(False)
        self.scanIntervalLength.setFrame(True)
        self.scanIntervalLength.setDecimals(3)
        self.scanIntervalLength.setMinimum(0.0)
        self.scanIntervalLength.setMaximum(20.0)
        self.scanIntervalLength.setSingleStep(0.01)
        self.scanIntervalLength.setProperty("value", QtCore.QVariant(0.02))
        self.scanIntervalLength.setObjectName("scanIntervalLength")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.scanIntervalLength)
        self.label_8 = QtGui.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtGui.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_9)
        self.stepLength = QtGui.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.stepLength.setFont(font)
        self.stepLength.setObjectName("stepLength")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.stepLength)
        self.numberPoints = QtGui.QSpinBox(self.formLayoutWidget_2)
        self.numberPoints.setMinimum(2)
        self.numberPoints.setProperty("value", QtCore.QVariant(7))
        self.numberPoints.setObjectName("numberPoints")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.numberPoints)
        self.countSpinBox = QtGui.QSpinBox(self.formLayoutWidget_2)
        self.countSpinBox.setMinimum(2)
        self.countSpinBox.setMaximum(999999999)
        self.countSpinBox.setSingleStep(10)
        self.countSpinBox.setProperty("value", QtCore.QVariant(50001))
        self.countSpinBox.setObjectName("countSpinBox")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.countSpinBox)
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 380, 60, 96))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.verticalLayoutWidget_3.setFont(font)
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ChangeCh0 = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ChangeCh0.setFont(font)
        self.ChangeCh0.setChecked(True)
        self.ChangeCh0.setObjectName("ChangeCh0")
        self.verticalLayout_3.addWidget(self.ChangeCh0)
        self.ChangeCh1 = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ChangeCh1.setFont(font)
        self.ChangeCh1.setObjectName("ChangeCh1")
        self.verticalLayout_3.addWidget(self.ChangeCh1)
        self.ChangeCh2 = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ChangeCh2.setFont(font)
        self.ChangeCh2.setChecked(True)
        self.ChangeCh2.setObjectName("ChangeCh2")
        self.verticalLayout_3.addWidget(self.ChangeCh2)
        self.ChangeCh3 = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.ChangeCh3.setEnabled(True)
        self.ChangeCh3.setObjectName("ChangeCh3")
        self.verticalLayout_3.addWidget(self.ChangeCh3)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 370, 240, 10))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 480, 240, 60))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.formLayoutWidget_3.setFont(font)
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtGui.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_10 = QtGui.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_10)
        self.DeltaV = QtGui.QDoubleSpinBox(self.formLayoutWidget_3)
        self.DeltaV.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.DeltaV.setFont(font)
        self.DeltaV.setWrapping(False)
        self.DeltaV.setFrame(True)
        self.DeltaV.setDecimals(4)
        self.DeltaV.setMinimum(-1.0)
        self.DeltaV.setMaximum(1.0)
        self.DeltaV.setSingleStep(0.001)
        self.DeltaV.setProperty("value", QtCore.QVariant(0.0))
        self.DeltaV.setObjectName("DeltaV")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.DeltaV)
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(90, 380, 140, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.ChangeV = QtGui.QPushButton(self.centralwidget)
        self.ChangeV.setGeometry(QtCore.QRect(110, 410, 80, 30))
        self.ChangeV.setObjectName("ChangeV")
        DACWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(DACWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 816, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        DACWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(DACWindow)
        self.statusbar.setObjectName("statusbar")
        DACWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(DACWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(DACWindow)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL("triggered()"), DACWindow.close)
        QtCore.QMetaObject.connectSlotsByName(DACWindow)
        DACWindow.setTabOrder(self.ch0SpinBox, self.ch1SpinBox)
        DACWindow.setTabOrder(self.ch1SpinBox, self.ch2SpinBox)
        DACWindow.setTabOrder(self.ch2SpinBox, self.ch3SpinBox)
        DACWindow.setTabOrder(self.ch3SpinBox, self.FixVDiffMMMM)
        DACWindow.setTabOrder(self.FixVDiffMMMM, self.FixVSumMMMM)
        DACWindow.setTabOrder(self.FixVSumMMMM, self.NoMMMM)
        DACWindow.setTabOrder(self.NoMMMM, self.countSpinBox)
        DACWindow.setTabOrder(self.countSpinBox, self.scanIntervalLength)
        DACWindow.setTabOrder(self.scanIntervalLength, self.numberPoints)
        DACWindow.setTabOrder(self.numberPoints, self.ChangeCh0)
        DACWindow.setTabOrder(self.ChangeCh0, self.ChangeCh1)
        DACWindow.setTabOrder(self.ChangeCh1, self.ChangeCh2)
        DACWindow.setTabOrder(self.ChangeCh2, self.ChangeCh3)
        DACWindow.setTabOrder(self.ChangeCh3, self.ChangeV)
        DACWindow.setTabOrder(self.ChangeV, self.DeltaV)

    def retranslateUi(self, DACWindow):
        DACWindow.setWindowTitle(QtGui.QApplication.translate("DACWindow", "Micromotion Minimization", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DACWindow", "Ch0 (RF)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("DACWindow", "Ch1 (DC)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("DACWindow", "Ch2 (Squeeze RF)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("DACWindow", "Ch3 (Squeeze RF)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("DACWindow", "Output voltages (V):", None, QtGui.QApplication.UnicodeUTF8))
        self.expectedCh3.setText(QtGui.QApplication.translate("DACWindow", "Ch3=0.000000 for DC=", None, QtGui.QApplication.UnicodeUTF8))
        self.FixVDiffMMMM.setText(QtGui.QApplication.translate("DACWindow", "Micromotion with fix voltage difference", None, QtGui.QApplication.UnicodeUTF8))
        self.FixVSumMMMM.setText(QtGui.QApplication.translate("DACWindow", "Micromotion with fix voltage sum", None, QtGui.QApplication.UnicodeUTF8))
        self.NoMMMM.setText(QtGui.QApplication.translate("DACWindow", "OFF", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("DACWindow", "Count trigger", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("DACWindow", "Scan-interval length", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("DACWindow", "Number of points", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("DACWindow", "Step length of each channel:", None, QtGui.QApplication.UnicodeUTF8))
        self.stepLength.setText(QtGui.QApplication.translate("DACWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.ChangeCh0.setText(QtGui.QApplication.translate("DACWindow", "Ch0", None, QtGui.QApplication.UnicodeUTF8))
        self.ChangeCh1.setText(QtGui.QApplication.translate("DACWindow", "Ch1", None, QtGui.QApplication.UnicodeUTF8))
        self.ChangeCh2.setText(QtGui.QApplication.translate("DACWindow", "Ch2", None, QtGui.QApplication.UnicodeUTF8))
        self.ChangeCh3.setText(QtGui.QApplication.translate("DACWindow", "Ch3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("DACWindow", "Change in voltage (V)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("DACWindow", "Variation of Voltage", None, QtGui.QApplication.UnicodeUTF8))
        self.ChangeV.setText(QtGui.QApplication.translate("DACWindow", "Change", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("DACWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("DACWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))

from matplotlibwidget import MatplotlibWidget
