# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pytdc_gui.ui'
#
# Created: Wed Apr 05 20:30:43 2017
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_TDCWindow(object):
    def setupUi(self, TDCWindow):
        TDCWindow.setObjectName("TDCWindow")
        TDCWindow.resize(1037, 733)
        self.centralwidget = QtGui.QWidget(TDCWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.measurement_tab = QtGui.QWidget()
        self.measurement_tab.setObjectName("measurement_tab")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.measurement_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.hist_plot = Qwt5.QwtPlot(self.measurement_tab)
        self.hist_plot.setObjectName("hist_plot")
        self.verticalLayout_2.addWidget(self.hist_plot)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.startButton = QtGui.QPushButton(self.measurement_tab)
        self.startButton.setObjectName("startButton")
        self.horizontalLayout_3.addWidget(self.startButton)
        self.pauseButton = QtGui.QPushButton(self.measurement_tab)
        self.pauseButton.setCheckable(True)
        self.pauseButton.setObjectName("pauseButton")
        self.horizontalLayout_3.addWidget(self.pauseButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.measurement_tab)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.startSpinBox = QtGui.QDoubleSpinBox(self.measurement_tab)
        self.startSpinBox.setMaximum(999999999.99)
        self.startSpinBox.setSingleStep(1000.0)
        self.startSpinBox.setObjectName("startSpinBox")
        self.gridLayout.addWidget(self.startSpinBox, 2, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.measurement_tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.stopSpinBox = QtGui.QDoubleSpinBox(self.measurement_tab)
        self.stopSpinBox.setMaximum(999999999.99)
        self.stopSpinBox.setSingleStep(20.0)
        self.stopSpinBox.setProperty("value", QtCore.QVariant(250.0))
        self.stopSpinBox.setObjectName("stopSpinBox")
        self.gridLayout.addWidget(self.stopSpinBox, 2, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.measurement_tab)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.stepSpinBox = QtGui.QDoubleSpinBox(self.measurement_tab)
        self.stepSpinBox.setMaximum(999999.99)
        self.stepSpinBox.setProperty("value", QtCore.QVariant(1.0))
        self.stepSpinBox.setObjectName("stepSpinBox")
        self.gridLayout.addWidget(self.stepSpinBox, 2, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.measurement_tab)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 3, 1, 1)
        self.refreshRateBox = QtGui.QSpinBox(self.measurement_tab)
        self.refreshRateBox.setMaximum(999999)
        self.refreshRateBox.setProperty("value", QtCore.QVariant(5000))
        self.refreshRateBox.setObjectName("refreshRateBox")
        self.gridLayout.addWidget(self.refreshRateBox, 2, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.saveButton = QtGui.QPushButton(self.measurement_tab)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout_2.addWidget(self.saveButton)
        self.filenameEdit = QtGui.QLineEdit(self.measurement_tab)
        self.filenameEdit.setObjectName("filenameEdit")
        self.horizontalLayout_2.addWidget(self.filenameEdit)
        self.filenameButton = QtGui.QToolButton(self.measurement_tab)
        self.filenameButton.setObjectName("filenameButton")
        self.horizontalLayout_2.addWidget(self.filenameButton)
        self.save_stampsBox = QtGui.QCheckBox(self.measurement_tab)
        self.save_stampsBox.setObjectName("save_stampsBox")
        self.horizontalLayout_2.addWidget(self.save_stampsBox)
        self.label_5 = QtGui.QLabel(self.measurement_tab)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.measurement_tab, "")
        self.calibration_tab = QtGui.QWidget()
        self.calibration_tab.setObjectName("calibration_tab")
        self.fine_start_plot = Qwt5.QwtPlot(self.calibration_tab)
        self.fine_start_plot.setGeometry(QtCore.QRect(10, 20, 691, 200))
        self.fine_start_plot.setObjectName("fine_start_plot")
        self.fine_stop_plot = Qwt5.QwtPlot(self.calibration_tab)
        self.fine_stop_plot.setGeometry(QtCore.QRect(10, 250, 681, 200))
        self.fine_stop_plot.setObjectName("fine_stop_plot")
        self.calibrateButton = QtGui.QPushButton(self.calibration_tab)
        self.calibrateButton.setGeometry(QtCore.QRect(50, 470, 91, 23))
        self.calibrateButton.setObjectName("calibrateButton")
        self.neventsBox = QtGui.QSpinBox(self.calibration_tab)
        self.neventsBox.setGeometry(QtCore.QRect(380, 470, 121, 20))
        self.neventsBox.setMinimum(1)
        self.neventsBox.setMaximum(99999999)
        self.neventsBox.setSingleStep(10000)
        self.neventsBox.setProperty("value", QtCore.QVariant(500000))
        self.neventsBox.setObjectName("neventsBox")
        self.label_4 = QtGui.QLabel(self.calibration_tab)
        self.label_4.setGeometry(QtCore.QRect(210, 470, 161, 16))
        self.label_4.setObjectName("label_4")
        self.horizontalLayoutWidget = QtGui.QWidget(self.calibration_tab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(210, 494, 291, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cstartBox = QtGui.QSpinBox(self.horizontalLayoutWidget)
        self.cstartBox.setMaximum(127)
        self.cstartBox.setObjectName("cstartBox")
        self.horizontalLayout.addWidget(self.cstartBox)
        self.cstopBox = QtGui.QSpinBox(self.horizontalLayoutWidget)
        self.cstopBox.setMaximum(127)
        self.cstopBox.setObjectName("cstopBox")
        self.horizontalLayout.addWidget(self.cstopBox)
        self.csetButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.csetButton.setObjectName("csetButton")
        self.horizontalLayout.addWidget(self.csetButton)
        self.tabWidget.addTab(self.calibration_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.status_label = QtGui.QLabel(self.centralwidget)
        self.status_label.setObjectName("status_label")
        self.verticalLayout.addWidget(self.status_label)
        TDCWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(TDCWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1037, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuData = QtGui.QMenu(self.menubar)
        self.menuData.setObjectName("menuData")
        self.menuMicromotion = QtGui.QMenu(self.menubar)
        self.menuMicromotion.setObjectName("menuMicromotion")
        TDCWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(TDCWindow)
        self.statusbar.setObjectName("statusbar")
        TDCWindow.setStatusBar(self.statusbar)
        self.actionFit = QtGui.QAction(TDCWindow)
        self.actionFit.setObjectName("actionFit")
        self.actionExit = QtGui.QAction(TDCWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionDAC = QtGui.QAction(TDCWindow)
        self.actionDAC.setObjectName("actionDAC")
        self.menuFile.addAction(self.actionExit)
        self.menuData.addAction(self.actionFit)
        self.menuMicromotion.addAction(self.actionDAC)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuData.menuAction())
        self.menubar.addAction(self.menuMicromotion.menuAction())

        self.retranslateUi(TDCWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL("triggered()"), TDCWindow.close)
        QtCore.QMetaObject.connectSlotsByName(TDCWindow)

    def retranslateUi(self, TDCWindow):
        TDCWindow.setWindowTitle(QtGui.QApplication.translate("TDCWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.startButton.setText(QtGui.QApplication.translate("TDCWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.pauseButton.setText(QtGui.QApplication.translate("TDCWindow", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("TDCWindow", "Histogram start, ns", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("TDCWindow", "Histogram stop, ns", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("TDCWindow", "Step, ns", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("TDCWindow", "Update rate, counts", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setText(QtGui.QApplication.translate("TDCWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.filenameButton.setText(QtGui.QApplication.translate("TDCWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.save_stampsBox.setText(QtGui.QApplication.translate("TDCWindow", "Save Timestamps", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("TDCWindow", "Timestamp filename", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.measurement_tab), QtGui.QApplication.translate("TDCWindow", "Measurement", None, QtGui.QApplication.UnicodeUTF8))
        self.calibrateButton.setText(QtGui.QApplication.translate("TDCWindow", "Calibrate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("TDCWindow", "Number of events for calibration:", None, QtGui.QApplication.UnicodeUTF8))
        self.csetButton.setText(QtGui.QApplication.translate("TDCWindow", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.calibration_tab), QtGui.QApplication.translate("TDCWindow", "Calibration", None, QtGui.QApplication.UnicodeUTF8))
        self.status_label.setText(QtGui.QApplication.translate("TDCWindow", "TDC Status", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("TDCWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuData.setTitle(QtGui.QApplication.translate("TDCWindow", "Data", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMicromotion.setTitle(QtGui.QApplication.translate("TDCWindow", "Micromotion", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFit.setText(QtGui.QApplication.translate("TDCWindow", "Fit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("TDCWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDAC.setText(QtGui.QApplication.translate("TDCWindow", "DAC", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import Qwt5
