# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sine_fit_ui.ui'
#
# Created: Wed Mar 22 15:10:51 2017
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_SineDialog(object):
    def setupUi(self, SineDialog):
        SineDialog.setObjectName("SineDialog")
        SineDialog.resize(227, 273)
        self.formLayoutWidget = QtGui.QWidget(SineDialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 180, 201, 81))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.aSpinBox = QtGui.QDoubleSpinBox(self.formLayoutWidget)
        self.aSpinBox.setMaximum(99999.99)
        self.aSpinBox.setSingleStep(10.0)
        self.aSpinBox.setProperty("value", QtCore.QVariant(100.0))
        self.aSpinBox.setObjectName("aSpinBox")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.aSpinBox)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.bSpinBox = QtGui.QDoubleSpinBox(self.formLayoutWidget)
        self.bSpinBox.setMaximum(9999.99)
        self.bSpinBox.setProperty("value", QtCore.QVariant(10.0))
        self.bSpinBox.setObjectName("bSpinBox")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.bSpinBox)
        self.label_3 = QtGui.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.PhiSpinBox = QtGui.QDoubleSpinBox(self.formLayoutWidget)
        self.PhiSpinBox.setMaximum(360.0)
        self.PhiSpinBox.setSingleStep(10.0)
        self.PhiSpinBox.setProperty("value", QtCore.QVariant(180.0))
        self.PhiSpinBox.setObjectName("PhiSpinBox")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.PhiSpinBox)
        self.doneButton = QtGui.QPushButton(SineDialog)
        self.doneButton.setGeometry(QtCore.QRect(130, 150, 75, 23))
        self.doneButton.setObjectName("doneButton")
        self.fitButton = QtGui.QPushButton(SineDialog)
        self.fitButton.setGeometry(QtCore.QRect(10, 150, 75, 23))
        self.fitButton.setObjectName("fitButton")
        self.label_4 = QtGui.QLabel(SineDialog)
        self.label_4.setGeometry(QtCore.QRect(30, 100, 151, 40))
        self.label_4.setObjectName("label_4")
        self.formLayoutWidget_2 = QtGui.QWidget(SineDialog)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 201, 94))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_5 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.xminSpinBox = QtGui.QDoubleSpinBox(self.formLayoutWidget_2)
        self.xminSpinBox.setMinimum(0.0)
        self.xminSpinBox.setMaximum(9999.99)
        self.xminSpinBox.setProperty("value", QtCore.QVariant(5.0))
        self.xminSpinBox.setObjectName("xminSpinBox")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.xminSpinBox)
        self.label_7 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_7)
        self.xmaxSpinBox = QtGui.QDoubleSpinBox(self.formLayoutWidget_2)
        self.xmaxSpinBox.setMaximum(1000000000.0)
        self.xmaxSpinBox.setProperty("value", QtCore.QVariant(225.0))
        self.xmaxSpinBox.setObjectName("xmaxSpinBox")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.xmaxSpinBox)
        self.fSpinBox = QtGui.QDoubleSpinBox(self.formLayoutWidget_2)
        self.fSpinBox.setDecimals(3)
        self.fSpinBox.setMaximum(100.0)
        self.fSpinBox.setSingleStep(0.1)
        self.fSpinBox.setProperty("value", QtCore.QVariant(30.0))
        self.fSpinBox.setObjectName("fSpinBox")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.fSpinBox)

        self.retranslateUi(SineDialog)
        QtCore.QObject.connect(self.doneButton, QtCore.SIGNAL("clicked()"), SineDialog.close)
        QtCore.QMetaObject.connectSlotsByName(SineDialog)
        SineDialog.setTabOrder(self.fSpinBox, self.xminSpinBox)
        SineDialog.setTabOrder(self.xminSpinBox, self.xmaxSpinBox)
        SineDialog.setTabOrder(self.xmaxSpinBox, self.fitButton)
        SineDialog.setTabOrder(self.fitButton, self.doneButton)
        SineDialog.setTabOrder(self.doneButton, self.aSpinBox)
        SineDialog.setTabOrder(self.aSpinBox, self.bSpinBox)
        SineDialog.setTabOrder(self.bSpinBox, self.PhiSpinBox)

    def retranslateUi(self, SineDialog):
        SineDialog.setWindowTitle(QtGui.QApplication.translate("SineDialog", "Sine Fit", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("SineDialog", "a", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("SineDialog", "b", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("SineDialog", "Φ", None, QtGui.QApplication.UnicodeUTF8))
        self.doneButton.setText(QtGui.QApplication.translate("SineDialog", "Done", None, QtGui.QApplication.UnicodeUTF8))
        self.fitButton.setText(QtGui.QApplication.translate("SineDialog", "Fit", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("SineDialog", "Fit: \n"
"y = a + b Sin(t * 2π * f + Φ) \n"
"in [xmin,xmax]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("SineDialog", "f (MHz)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("SineDialog", "xmin (nsec)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("SineDialog", "xmax (nsec)", None, QtGui.QApplication.UnicodeUTF8))

