# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CamGUI.ui'
#
# Created: Fri Oct 30 14:18:59 2015
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Cam(object):
    def setupUi(self, Cam):
        Cam.setObjectName("Cam")
        Cam.resize(745, 541)
        Cam.setCursor(QtCore.Qt.ArrowCursor)
        self.exitButton = QtGui.QPushButton(Cam)
        self.exitButton.setGeometry(QtCore.QRect(10, 200, 70, 20))
        self.exitButton.setObjectName("exitButton")
        self.gridLayoutWidget = QtGui.QWidget(Cam)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 160, 131))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.xspinBox = QtGui.QSpinBox(self.gridLayoutWidget)
        self.xspinBox.setMinimum(0)
        self.xspinBox.setMaximum(512)
        self.xspinBox.setSingleStep(1)
        self.xspinBox.setProperty("value", QtCore.QVariant(0))
        self.xspinBox.setObjectName("xspinBox")
        self.gridLayout.addWidget(self.xspinBox, 1, 1, 1, 1)
        self.yspinBox = QtGui.QSpinBox(self.gridLayoutWidget)
        self.yspinBox.setMinimum(0)
        self.yspinBox.setMaximum(512)
        self.yspinBox.setSingleStep(1)
        self.yspinBox.setProperty("value", QtCore.QVariant(0))
        self.yspinBox.setObjectName("yspinBox")
        self.gridLayout.addWidget(self.yspinBox, 2, 1, 1, 1)
        self.xSizespinBox = QtGui.QSpinBox(self.gridLayoutWidget)
        self.xSizespinBox.setMinimum(1)
        self.xSizespinBox.setMaximum(512)
        self.xSizespinBox.setSingleStep(1)
        self.xSizespinBox.setProperty("value", QtCore.QVariant(512))
        self.xSizespinBox.setObjectName("xSizespinBox")
        self.gridLayout.addWidget(self.xSizespinBox, 3, 1, 1, 1)
        self.ySizespinBox = QtGui.QSpinBox(self.gridLayoutWidget)
        self.ySizespinBox.setMinimum(1)
        self.ySizespinBox.setMaximum(512)
        self.ySizespinBox.setSingleStep(1)
        self.ySizespinBox.setProperty("value", QtCore.QVariant(512))
        self.ySizespinBox.setObjectName("ySizespinBox")
        self.gridLayout.addWidget(self.ySizespinBox, 4, 1, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.applyROIButton = QtGui.QPushButton(self.gridLayoutWidget)
        self.applyROIButton.setCursor(QtCore.Qt.PointingHandCursor)
        self.applyROIButton.setObjectName("applyROIButton")
        self.gridLayout.addWidget(self.applyROIButton, 0, 1, 1, 1)
        self.image = QtGui.QLabel(Cam)
        self.image.setGeometry(QtCore.QRect(220, 20, 512, 512))
        self.image.setCursor(QtCore.Qt.CrossCursor)
        self.image.setObjectName("image")
        self.startButton = QtGui.QPushButton(Cam)
        self.startButton.setGeometry(QtCore.QRect(10, 170, 70, 20))
        self.startButton.setObjectName("startButton")
        self.gridLayoutWidget_2 = QtGui.QWidget(Cam)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 260, 160, 79))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.POIxspinBox = QtGui.QSpinBox(self.gridLayoutWidget_2)
        self.POIxspinBox.setMinimum(1)
        self.POIxspinBox.setMaximum(512)
        self.POIxspinBox.setProperty("value", QtCore.QVariant(255))
        self.POIxspinBox.setObjectName("POIxspinBox")
        self.gridLayout_2.addWidget(self.POIxspinBox, 1, 1, 1, 1)
        self.POIyspinBox = QtGui.QSpinBox(self.gridLayoutWidget_2)
        self.POIyspinBox.setMinimum(1)
        self.POIyspinBox.setMaximum(512)
        self.POIyspinBox.setProperty("value", QtCore.QVariant(255))
        self.POIyspinBox.setObjectName("POIyspinBox")
        self.gridLayout_2.addWidget(self.POIyspinBox, 2, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.showPOIButton = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.showPOIButton.setCursor(QtCore.Qt.PointingHandCursor)
        self.showPOIButton.setObjectName("showPOIButton")
        self.gridLayout_2.addWidget(self.showPOIButton, 0, 1, 1, 1)
        self.intensityLabel = QtGui.QLabel(Cam)
        self.intensityLabel.setGeometry(QtCore.QRect(10, 340, 160, 25))
        self.intensityLabel.setObjectName("intensityLabel")
        self.label_8 = QtGui.QLabel(Cam)
        self.label_8.setGeometry(QtCore.QRect(9, 370, 75, 20))
        self.label_8.setObjectName("label_8")
        self.exposurespinBox = QtGui.QSpinBox(Cam)
        self.exposurespinBox.setGeometry(QtCore.QRect(90, 370, 77, 20))
        self.exposurespinBox.setMinimum(1)
        self.exposurespinBox.setMaximum(10000)
        self.exposurespinBox.setSingleStep(100)
        self.exposurespinBox.setProperty("value", QtCore.QVariant(500))
        self.exposurespinBox.setObjectName("exposurespinBox")
        self.propertylabel = QtGui.QLabel(Cam)
        self.propertylabel.setGeometry(QtCore.QRect(10, 420, 160, 20))
        self.propertylabel.setObjectName("propertylabel")
        self.propertycomboBox = QtGui.QComboBox(Cam)
        self.propertycomboBox.setGeometry(QtCore.QRect(10, 400, 160, 20))
        self.propertycomboBox.setObjectName("propertycomboBox")
        self.verticalLayoutWidget = QtGui.QWidget(Cam)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(90, 160, 79, 89))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cameraButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.cameraButton.setObjectName("cameraButton")
        self.verticalLayout.addWidget(self.cameraButton)
        self.PMTButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.PMTButton.setObjectName("PMTButton")
        self.verticalLayout.addWidget(self.PMTButton)
        self.ResetButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.ResetButton.setObjectName("ResetButton")
        self.verticalLayout.addWidget(self.ResetButton)

        self.retranslateUi(Cam)
        QtCore.QObject.connect(self.exitButton, QtCore.SIGNAL("clicked()"), Cam.close)
        QtCore.QMetaObject.connectSlotsByName(Cam)
        Cam.setTabOrder(self.applyROIButton, self.xspinBox)
        Cam.setTabOrder(self.xspinBox, self.yspinBox)
        Cam.setTabOrder(self.yspinBox, self.xSizespinBox)
        Cam.setTabOrder(self.xSizespinBox, self.ySizespinBox)
        Cam.setTabOrder(self.ySizespinBox, self.startButton)
        Cam.setTabOrder(self.startButton, self.exitButton)
        Cam.setTabOrder(self.exitButton, self.cameraButton)
        Cam.setTabOrder(self.cameraButton, self.PMTButton)
        Cam.setTabOrder(self.PMTButton, self.ResetButton)
        Cam.setTabOrder(self.ResetButton, self.showPOIButton)
        Cam.setTabOrder(self.showPOIButton, self.POIxspinBox)
        Cam.setTabOrder(self.POIxspinBox, self.POIyspinBox)
        Cam.setTabOrder(self.POIyspinBox, self.exposurespinBox)
        Cam.setTabOrder(self.exposurespinBox, self.propertycomboBox)

    def retranslateUi(self, Cam):
        Cam.setWindowTitle(QtGui.QApplication.translate("Cam", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.exitButton.setText(QtGui.QApplication.translate("Cam", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Cam", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Cam", "y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Cam", "xSize", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Cam", "ySize", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Cam", "ROI", None, QtGui.QApplication.UnicodeUTF8))
        self.applyROIButton.setText(QtGui.QApplication.translate("Cam", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.image.setText(QtGui.QApplication.translate("Cam", "Image", None, QtGui.QApplication.UnicodeUTF8))
        self.startButton.setText(QtGui.QApplication.translate("Cam", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Cam", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Cam", "y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Cam", "POI", None, QtGui.QApplication.UnicodeUTF8))
        self.showPOIButton.setText(QtGui.QApplication.translate("Cam", "Show", None, QtGui.QApplication.UnicodeUTF8))
        self.intensityLabel.setText(QtGui.QApplication.translate("Cam", "Intensity: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Cam", "Exposure (ms):", None, QtGui.QApplication.UnicodeUTF8))
        self.propertylabel.setText(QtGui.QApplication.translate("Cam", "Property", None, QtGui.QApplication.UnicodeUTF8))
        self.cameraButton.setText(QtGui.QApplication.translate("Cam", "Camera", None, QtGui.QApplication.UnicodeUTF8))
        self.PMTButton.setText(QtGui.QApplication.translate("Cam", "PMT", None, QtGui.QApplication.UnicodeUTF8))
        self.ResetButton.setText(QtGui.QApplication.translate("Cam", "Reset", None, QtGui.QApplication.UnicodeUTF8))

