# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'display_counters_ui.ui'
#
# Created: Sat Jun 28 23:28:09 2014
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_DisplayCounterDialog(object):
    def setupUi(self, DisplayCounterDialog):
        DisplayCounterDialog.setObjectName("DisplayCounterDialog")
        DisplayCounterDialog.resize(279, 326)
        self.buttonBox = QtGui.QDialogButtonBox(DisplayCounterDialog)
        self.buttonBox.setGeometry(QtCore.QRect(50, 280, 181, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayoutWidget = QtGui.QWidget(DisplayCounterDialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 20, 227, 241))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 7, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 8, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 2, 1, 1)
        self.cntav1 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.cntav1.setEnabled(False)
        self.cntav1.setObjectName("cntav1")
        self.gridLayout.addWidget(self.cntav1, 1, 1, 1, 1)
        self.cntav2 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.cntav2.setObjectName("cntav2")
        self.gridLayout.addWidget(self.cntav2, 2, 1, 1, 1)
        self.cntav3 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.cntav3.setObjectName("cntav3")
        self.gridLayout.addWidget(self.cntav3, 3, 1, 1, 1)
        self.cntav4 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.cntav4.setObjectName("cntav4")
        self.gridLayout.addWidget(self.cntav4, 4, 1, 1, 1)
        self.cntav5 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.cntav5.setObjectName("cntav5")
        self.gridLayout.addWidget(self.cntav5, 5, 1, 1, 1)
        self.cntav6 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.cntav6.setObjectName("cntav6")
        self.gridLayout.addWidget(self.cntav6, 6, 1, 1, 1)
        self.cntav7 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.cntav7.setObjectName("cntav7")
        self.gridLayout.addWidget(self.cntav7, 7, 1, 1, 1)
        self.cntav8 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.cntav8.setObjectName("cntav8")
        self.gridLayout.addWidget(self.cntav8, 8, 1, 1, 1)
        self.cntth1 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.cntth1.setEnabled(False)
        self.cntth1.setObjectName("cntth1")
        self.gridLayout.addWidget(self.cntth1, 1, 2, 1, 1)
        self.cntth2 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.cntth2.setObjectName("cntth2")
        self.gridLayout.addWidget(self.cntth2, 2, 2, 1, 1)
        self.cntth3 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.cntth3.setObjectName("cntth3")
        self.gridLayout.addWidget(self.cntth3, 3, 2, 1, 1)
        self.cntth4 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.cntth4.setObjectName("cntth4")
        self.gridLayout.addWidget(self.cntth4, 4, 2, 1, 1)
        self.cntth5 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.cntth5.setObjectName("cntth5")
        self.gridLayout.addWidget(self.cntth5, 5, 2, 1, 1)
        self.cntth6 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.cntth6.setObjectName("cntth6")
        self.gridLayout.addWidget(self.cntth6, 6, 2, 1, 1)
        self.cntth7 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.cntth7.setObjectName("cntth7")
        self.gridLayout.addWidget(self.cntth7, 7, 2, 1, 1)
        self.cntth8 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.cntth8.setObjectName("cntth8")
        self.gridLayout.addWidget(self.cntth8, 8, 2, 1, 1)

        self.retranslateUi(DisplayCounterDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), DisplayCounterDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), DisplayCounterDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(DisplayCounterDialog)

    def retranslateUi(self, DisplayCounterDialog):
        DisplayCounterDialog.setWindowTitle(QtGui.QApplication.translate("DisplayCounterDialog", "Counters to display", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DisplayCounterDialog", "Counter 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("DisplayCounterDialog", "Counter 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("DisplayCounterDialog", "Counter 3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("DisplayCounterDialog", "Counter 4", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("DisplayCounterDialog", "Counter 5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("DisplayCounterDialog", "Counter 6", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("DisplayCounterDialog", "Counter 7", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("DisplayCounterDialog", "Counter 8", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("DisplayCounterDialog", "Average", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("DisplayCounterDialog", "Above threshold", None, QtGui.QApplication.UnicodeUTF8))

