# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guipm.ui'
#
# Created: Wed Aug 14 11:46:05 2013
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_DDSDialog(object):
    def setupUi(self, DDSDialog):
        DDSDialog.setObjectName("DDSDialog")
        DDSDialog.setEnabled(True)
        DDSDialog.resize(441, 305)
        DDSDialog.setMinimumSize(QtCore.QSize(405, 0))
        self.exitButton = QtGui.QPushButton(DDSDialog)
        self.exitButton.setGeometry(QtCore.QRect(320, 130, 75, 23))
        self.exitButton.setCursor(QtCore.Qt.ArrowCursor)
        self.exitButton.setMouseTracking(False)
        self.exitButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.exitButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.exitButton.setAutoDefault(False)
        self.exitButton.setObjectName("exitButton")
        self.sernumBox = QtGui.QComboBox(DDSDialog)
        self.sernumBox.setGeometry(QtCore.QRect(290, 0, 91, 20))
        self.sernumBox.setObjectName("sernumBox")
        self.label_10 = QtGui.QLabel(DDSDialog)
        self.label_10.setGeometry(QtCore.QRect(190, 0, 96, 17))
        self.label_10.setObjectName("label_10")
        self.phase_profiles = QtGui.QWidget(DDSDialog)
        self.phase_profiles.setEnabled(True)
        self.phase_profiles.setGeometry(QtCore.QRect(30, 30, 251, 128))
        self.phase_profiles.setObjectName("phase_profiles")
        self.gridLayout_2 = QtGui.QGridLayout(self.phase_profiles)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_11 = QtGui.QLabel(self.phase_profiles)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 2, 5, 1, 1)
        self.label_26 = QtGui.QLabel(self.phase_profiles)
        self.label_26.setObjectName("label_26")
        self.gridLayout_2.addWidget(self.label_26, 0, 5, 1, 1)
        self.line_7 = QtGui.QFrame(self.phase_profiles)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_2.addWidget(self.line_7, 1, 6, 1, 1)
        self.phase0ch0 = QtGui.QDoubleSpinBox(self.phase_profiles)
        self.phase0ch0.setEnabled(True)
        self.phase0ch0.setMouseTracking(False)
        self.phase0ch0.setWrapping(False)
        self.phase0ch0.setFrame(True)
        self.phase0ch0.setMaximum(360.0)
        self.phase0ch0.setSingleStep(10.0)
        self.phase0ch0.setObjectName("phase0ch0")
        self.gridLayout_2.addWidget(self.phase0ch0, 2, 2, 1, 1)
        self.line_8 = QtGui.QFrame(self.phase_profiles)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout_2.addWidget(self.line_8, 1, 0, 1, 1)
        self.line_9 = QtGui.QFrame(self.phase_profiles)
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout_2.addWidget(self.line_9, 1, 1, 1, 1)
        self.label_35 = QtGui.QLabel(self.phase_profiles)
        self.label_35.setObjectName("label_35")
        self.gridLayout_2.addWidget(self.label_35, 4, 4, 1, 1)
        self.line_10 = QtGui.QFrame(self.phase_profiles)
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout_2.addWidget(self.line_10, 1, 2, 1, 1)
        self.line_11 = QtGui.QFrame(self.phase_profiles)
        self.line_11.setFrameShape(QtGui.QFrame.HLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout_2.addWidget(self.line_11, 1, 4, 1, 1)
        self.line_12 = QtGui.QFrame(self.phase_profiles)
        self.line_12.setFrameShape(QtGui.QFrame.HLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.gridLayout_2.addWidget(self.line_12, 1, 5, 1, 1)
        self.label_37 = QtGui.QLabel(self.phase_profiles)
        self.label_37.setObjectName("label_37")
        self.gridLayout_2.addWidget(self.label_37, 5, 5, 1, 1)
        self.label_15 = QtGui.QLabel(self.phase_profiles)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 4, 5, 1, 1)
        self.phase1ch0 = QtGui.QDoubleSpinBox(self.phase_profiles)
        self.phase1ch0.setMaximum(360.0)
        self.phase1ch0.setSingleStep(10.0)
        self.phase1ch0.setObjectName("phase1ch0")
        self.gridLayout_2.addWidget(self.phase1ch0, 3, 2, 1, 1)
        self.label_12 = QtGui.QLabel(self.phase_profiles)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 3, 4, 1, 1)
        self.phase2ch0 = QtGui.QDoubleSpinBox(self.phase_profiles)
        self.phase2ch0.setMaximum(360.0)
        self.phase2ch0.setSingleStep(10.0)
        self.phase2ch0.setObjectName("phase2ch0")
        self.gridLayout_2.addWidget(self.phase2ch0, 4, 2, 1, 1)
        self.label_25 = QtGui.QLabel(self.phase_profiles)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 0, 4, 1, 1)
        self.label_24 = QtGui.QLabel(self.phase_profiles)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 0, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.phase_profiles)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 2, 4, 1, 1)
        self.label_23 = QtGui.QLabel(self.phase_profiles)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 0, 0, 1, 1)
        self.label_36 = QtGui.QLabel(self.phase_profiles)
        self.label_36.setObjectName("label_36")
        self.gridLayout_2.addWidget(self.label_36, 5, 4, 1, 1)
        self.label_34 = QtGui.QLabel(self.phase_profiles)
        self.label_34.setObjectName("label_34")
        self.gridLayout_2.addWidget(self.label_34, 3, 5, 1, 1)
        self.line_13 = QtGui.QFrame(self.phase_profiles)
        self.line_13.setFrameShape(QtGui.QFrame.VLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.gridLayout_2.addWidget(self.line_13, 0, 3, 1, 1)
        self.line_14 = QtGui.QFrame(self.phase_profiles)
        self.line_14.setFrameShape(QtGui.QFrame.VLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.gridLayout_2.addWidget(self.line_14, 2, 3, 1, 1)
        self.line_15 = QtGui.QFrame(self.phase_profiles)
        self.line_15.setFrameShape(QtGui.QFrame.VLine)
        self.line_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.gridLayout_2.addWidget(self.line_15, 3, 3, 1, 1)
        self.line_16 = QtGui.QFrame(self.phase_profiles)
        self.line_16.setFrameShape(QtGui.QFrame.VLine)
        self.line_16.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.gridLayout_2.addWidget(self.line_16, 4, 3, 1, 1)
        self.line_17 = QtGui.QFrame(self.phase_profiles)
        self.line_17.setFrameShape(QtGui.QFrame.VLine)
        self.line_17.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.gridLayout_2.addWidget(self.line_17, 5, 3, 1, 1)
        self.label_38 = QtGui.QLabel(self.phase_profiles)
        self.label_38.setObjectName("label_38")
        self.gridLayout_2.addWidget(self.label_38, 4, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.phase_profiles)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 4, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.phase_profiles)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 3, 0, 1, 1)
        self.label_40 = QtGui.QLabel(self.phase_profiles)
        self.label_40.setObjectName("label_40")
        self.gridLayout_2.addWidget(self.label_40, 3, 1, 1, 1)
        self.label_39 = QtGui.QLabel(self.phase_profiles)
        self.label_39.setObjectName("label_39")
        self.gridLayout_2.addWidget(self.label_39, 5, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.phase_profiles)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 2, 1, 1, 1)
        self.label_41 = QtGui.QLabel(self.phase_profiles)
        self.label_41.setObjectName("label_41")
        self.gridLayout_2.addWidget(self.label_41, 5, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.phase_profiles)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 2, 0, 1, 1)
        self.label_27 = QtGui.QLabel(self.phase_profiles)
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 0, 2, 1, 1)
        self.label_28 = QtGui.QLabel(self.phase_profiles)
        self.label_28.setObjectName("label_28")
        self.gridLayout_2.addWidget(self.label_28, 0, 6, 1, 1)
        self.phase0ch1 = QtGui.QDoubleSpinBox(self.phase_profiles)
        self.phase0ch1.setMaximum(360.0)
        self.phase0ch1.setSingleStep(10.0)
        self.phase0ch1.setObjectName("phase0ch1")
        self.gridLayout_2.addWidget(self.phase0ch1, 2, 6, 1, 1)
        self.phase1ch1 = QtGui.QDoubleSpinBox(self.phase_profiles)
        self.phase1ch1.setMaximum(360.0)
        self.phase1ch1.setSingleStep(10.0)
        self.phase1ch1.setObjectName("phase1ch1")
        self.gridLayout_2.addWidget(self.phase1ch1, 3, 6, 1, 1)
        self.phase2ch1 = QtGui.QDoubleSpinBox(self.phase_profiles)
        self.phase2ch1.setMaximum(360.0)
        self.phase2ch1.setSingleStep(10.0)
        self.phase2ch1.setObjectName("phase2ch1")
        self.gridLayout_2.addWidget(self.phase2ch1, 4, 6, 1, 1)
        self.phase3ch1 = QtGui.QDoubleSpinBox(self.phase_profiles)
        self.phase3ch1.setMaximum(360.0)
        self.phase3ch1.setSingleStep(10.0)
        self.phase3ch1.setObjectName("phase3ch1")
        self.gridLayout_2.addWidget(self.phase3ch1, 5, 6, 1, 1)
        self.phase3ch0 = QtGui.QDoubleSpinBox(self.phase_profiles)
        self.phase3ch0.setMaximum(360.0)
        self.phase3ch0.setSingleStep(10.0)
        self.phase3ch0.setObjectName("phase3ch0")
        self.gridLayout_2.addWidget(self.phase3ch0, 5, 2, 1, 1)
        self.PhaseModulation = QtGui.QRadioButton(DDSDialog)
        self.PhaseModulation.setGeometry(QtCore.QRect(300, 60, 111, 17))
        self.PhaseModulation.setMinimumSize(QtCore.QSize(111, 17))
        self.PhaseModulation.setObjectName("PhaseModulation")
        self.SingleTone = QtGui.QRadioButton(DDSDialog)
        self.SingleTone.setGeometry(QtCore.QRect(300, 40, 82, 17))
        self.SingleTone.setMinimumSize(QtCore.QSize(82, 17))
        self.SingleTone.setChecked(True)
        self.SingleTone.setObjectName("SingleTone")
        self.frequency_profiles = QtGui.QWidget(DDSDialog)
        self.frequency_profiles.setEnabled(True)
        self.frequency_profiles.setGeometry(QtCore.QRect(30, 170, 301, 128))
        self.frequency_profiles.setMinimumSize(QtCore.QSize(251, 0))
        self.frequency_profiles.setObjectName("frequency_profiles")
        self.gridLayout_3 = QtGui.QGridLayout(self.frequency_profiles)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_19 = QtGui.QLabel(self.frequency_profiles)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 2, 5, 1, 1)
        self.label_29 = QtGui.QLabel(self.frequency_profiles)
        self.label_29.setObjectName("label_29")
        self.gridLayout_3.addWidget(self.label_29, 0, 5, 1, 1)
        self.line_18 = QtGui.QFrame(self.frequency_profiles)
        self.line_18.setFrameShape(QtGui.QFrame.HLine)
        self.line_18.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.gridLayout_3.addWidget(self.line_18, 1, 6, 1, 1)
        self.freq0ch0 = QtGui.QDoubleSpinBox(self.frequency_profiles)
        self.freq0ch0.setEnabled(True)
        self.freq0ch0.setMouseTracking(False)
        self.freq0ch0.setWrapping(False)
        self.freq0ch0.setFrame(True)
        self.freq0ch0.setMaximum(200000000.0)
        self.freq0ch0.setSingleStep(1000000.0)
        self.freq0ch0.setProperty("value", QtCore.QVariant(10000000.0))
        self.freq0ch0.setObjectName("freq0ch0")
        self.gridLayout_3.addWidget(self.freq0ch0, 2, 2, 1, 1)
        self.line_19 = QtGui.QFrame(self.frequency_profiles)
        self.line_19.setFrameShape(QtGui.QFrame.HLine)
        self.line_19.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.gridLayout_3.addWidget(self.line_19, 1, 0, 1, 1)
        self.line_20 = QtGui.QFrame(self.frequency_profiles)
        self.line_20.setFrameShape(QtGui.QFrame.HLine)
        self.line_20.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.gridLayout_3.addWidget(self.line_20, 1, 1, 1, 1)
        self.label_42 = QtGui.QLabel(self.frequency_profiles)
        self.label_42.setObjectName("label_42")
        self.gridLayout_3.addWidget(self.label_42, 4, 4, 1, 1)
        self.line_21 = QtGui.QFrame(self.frequency_profiles)
        self.line_21.setFrameShape(QtGui.QFrame.HLine)
        self.line_21.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.gridLayout_3.addWidget(self.line_21, 1, 2, 1, 1)
        self.line_22 = QtGui.QFrame(self.frequency_profiles)
        self.line_22.setFrameShape(QtGui.QFrame.HLine)
        self.line_22.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.gridLayout_3.addWidget(self.line_22, 1, 4, 1, 1)
        self.line_23 = QtGui.QFrame(self.frequency_profiles)
        self.line_23.setFrameShape(QtGui.QFrame.HLine)
        self.line_23.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.gridLayout_3.addWidget(self.line_23, 1, 5, 1, 1)
        self.label_43 = QtGui.QLabel(self.frequency_profiles)
        self.label_43.setObjectName("label_43")
        self.gridLayout_3.addWidget(self.label_43, 5, 5, 1, 1)
        self.label_20 = QtGui.QLabel(self.frequency_profiles)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 4, 5, 1, 1)
        self.freq1ch0 = QtGui.QDoubleSpinBox(self.frequency_profiles)
        self.freq1ch0.setMaximum(200000000.0)
        self.freq1ch0.setSingleStep(1000000.0)
        self.freq1ch0.setProperty("value", QtCore.QVariant(10000000.0))
        self.freq1ch0.setObjectName("freq1ch0")
        self.gridLayout_3.addWidget(self.freq1ch0, 3, 2, 1, 1)
        self.label_21 = QtGui.QLabel(self.frequency_profiles)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 3, 4, 1, 1)
        self.freq2ch0 = QtGui.QDoubleSpinBox(self.frequency_profiles)
        self.freq2ch0.setMaximum(200000000.0)
        self.freq2ch0.setSingleStep(1000000.0)
        self.freq2ch0.setProperty("value", QtCore.QVariant(10000000.0))
        self.freq2ch0.setObjectName("freq2ch0")
        self.gridLayout_3.addWidget(self.freq2ch0, 4, 2, 1, 1)
        self.label_30 = QtGui.QLabel(self.frequency_profiles)
        self.label_30.setObjectName("label_30")
        self.gridLayout_3.addWidget(self.label_30, 0, 4, 1, 1)
        self.label_31 = QtGui.QLabel(self.frequency_profiles)
        self.label_31.setObjectName("label_31")
        self.gridLayout_3.addWidget(self.label_31, 0, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.frequency_profiles)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 2, 4, 1, 1)
        self.label_32 = QtGui.QLabel(self.frequency_profiles)
        self.label_32.setObjectName("label_32")
        self.gridLayout_3.addWidget(self.label_32, 0, 0, 1, 1)
        self.label_44 = QtGui.QLabel(self.frequency_profiles)
        self.label_44.setObjectName("label_44")
        self.gridLayout_3.addWidget(self.label_44, 5, 4, 1, 1)
        self.label_45 = QtGui.QLabel(self.frequency_profiles)
        self.label_45.setObjectName("label_45")
        self.gridLayout_3.addWidget(self.label_45, 3, 5, 1, 1)
        self.line_24 = QtGui.QFrame(self.frequency_profiles)
        self.line_24.setFrameShape(QtGui.QFrame.VLine)
        self.line_24.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_24.setObjectName("line_24")
        self.gridLayout_3.addWidget(self.line_24, 0, 3, 1, 1)
        self.line_25 = QtGui.QFrame(self.frequency_profiles)
        self.line_25.setFrameShape(QtGui.QFrame.VLine)
        self.line_25.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_25.setObjectName("line_25")
        self.gridLayout_3.addWidget(self.line_25, 2, 3, 1, 1)
        self.line_26 = QtGui.QFrame(self.frequency_profiles)
        self.line_26.setFrameShape(QtGui.QFrame.VLine)
        self.line_26.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_26.setObjectName("line_26")
        self.gridLayout_3.addWidget(self.line_26, 3, 3, 1, 1)
        self.line_27 = QtGui.QFrame(self.frequency_profiles)
        self.line_27.setFrameShape(QtGui.QFrame.VLine)
        self.line_27.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_27.setObjectName("line_27")
        self.gridLayout_3.addWidget(self.line_27, 4, 3, 1, 1)
        self.line_28 = QtGui.QFrame(self.frequency_profiles)
        self.line_28.setFrameShape(QtGui.QFrame.VLine)
        self.line_28.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_28.setObjectName("line_28")
        self.gridLayout_3.addWidget(self.line_28, 5, 3, 1, 1)
        self.label_46 = QtGui.QLabel(self.frequency_profiles)
        self.label_46.setObjectName("label_46")
        self.gridLayout_3.addWidget(self.label_46, 4, 0, 1, 1)
        self.label_33 = QtGui.QLabel(self.frequency_profiles)
        self.label_33.setObjectName("label_33")
        self.gridLayout_3.addWidget(self.label_33, 4, 1, 1, 1)
        self.label_47 = QtGui.QLabel(self.frequency_profiles)
        self.label_47.setObjectName("label_47")
        self.gridLayout_3.addWidget(self.label_47, 3, 0, 1, 1)
        self.label_48 = QtGui.QLabel(self.frequency_profiles)
        self.label_48.setObjectName("label_48")
        self.gridLayout_3.addWidget(self.label_48, 3, 1, 1, 1)
        self.label_49 = QtGui.QLabel(self.frequency_profiles)
        self.label_49.setObjectName("label_49")
        self.gridLayout_3.addWidget(self.label_49, 5, 0, 1, 1)
        self.label_50 = QtGui.QLabel(self.frequency_profiles)
        self.label_50.setObjectName("label_50")
        self.gridLayout_3.addWidget(self.label_50, 2, 1, 1, 1)
        self.label_51 = QtGui.QLabel(self.frequency_profiles)
        self.label_51.setObjectName("label_51")
        self.gridLayout_3.addWidget(self.label_51, 5, 1, 1, 1)
        self.label_52 = QtGui.QLabel(self.frequency_profiles)
        self.label_52.setObjectName("label_52")
        self.gridLayout_3.addWidget(self.label_52, 2, 0, 1, 1)
        self.label_53 = QtGui.QLabel(self.frequency_profiles)
        self.label_53.setObjectName("label_53")
        self.gridLayout_3.addWidget(self.label_53, 0, 2, 1, 1)
        self.label_54 = QtGui.QLabel(self.frequency_profiles)
        self.label_54.setObjectName("label_54")
        self.gridLayout_3.addWidget(self.label_54, 0, 6, 1, 1)
        self.freq0ch1 = QtGui.QDoubleSpinBox(self.frequency_profiles)
        self.freq0ch1.setMaximum(200000000.0)
        self.freq0ch1.setSingleStep(1000000.0)
        self.freq0ch1.setProperty("value", QtCore.QVariant(10000000.0))
        self.freq0ch1.setObjectName("freq0ch1")
        self.gridLayout_3.addWidget(self.freq0ch1, 2, 6, 1, 1)
        self.freq1ch1 = QtGui.QDoubleSpinBox(self.frequency_profiles)
        self.freq1ch1.setMaximum(200000000.0)
        self.freq1ch1.setSingleStep(1000000.0)
        self.freq1ch1.setProperty("value", QtCore.QVariant(10000000.0))
        self.freq1ch1.setObjectName("freq1ch1")
        self.gridLayout_3.addWidget(self.freq1ch1, 3, 6, 1, 1)
        self.freq2ch1 = QtGui.QDoubleSpinBox(self.frequency_profiles)
        self.freq2ch1.setMaximum(200000000.0)
        self.freq2ch1.setSingleStep(1000000.0)
        self.freq2ch1.setProperty("value", QtCore.QVariant(10000000.0))
        self.freq2ch1.setObjectName("freq2ch1")
        self.gridLayout_3.addWidget(self.freq2ch1, 4, 6, 1, 1)
        self.freq3ch1 = QtGui.QDoubleSpinBox(self.frequency_profiles)
        self.freq3ch1.setMaximum(200000000.0)
        self.freq3ch1.setSingleStep(1000000.0)
        self.freq3ch1.setProperty("value", QtCore.QVariant(10000000.0))
        self.freq3ch1.setObjectName("freq3ch1")
        self.gridLayout_3.addWidget(self.freq3ch1, 5, 6, 1, 1)
        self.freq3ch0 = QtGui.QDoubleSpinBox(self.frequency_profiles)
        self.freq3ch0.setMaximum(200000000.0)
        self.freq3ch0.setSingleStep(1000000.0)
        self.freq3ch0.setProperty("value", QtCore.QVariant(10000000.0))
        self.freq3ch0.setObjectName("freq3ch0")
        self.gridLayout_3.addWidget(self.freq3ch0, 5, 2, 1, 1)
        self.FrequencyModulation = QtGui.QRadioButton(DDSDialog)
        self.FrequencyModulation.setGeometry(QtCore.QRect(300, 80, 131, 17))
        self.FrequencyModulation.setMinimumSize(QtCore.QSize(111, 17))
        self.FrequencyModulation.setObjectName("FrequencyModulation")

        self.retranslateUi(DDSDialog)
        QtCore.QObject.connect(self.exitButton, QtCore.SIGNAL("clicked()"), DDSDialog.close)
        QtCore.QObject.connect(self.FrequencyModulation, QtCore.SIGNAL("clicked()"), self.phase_profiles.hide)
        QtCore.QObject.connect(self.FrequencyModulation, QtCore.SIGNAL("clicked()"), self.frequency_profiles.show)
        QtCore.QObject.connect(self.PhaseModulation, QtCore.SIGNAL("clicked()"), self.phase_profiles.show)
        QtCore.QObject.connect(self.PhaseModulation, QtCore.SIGNAL("clicked()"), self.frequency_profiles.hide)
        QtCore.QObject.connect(self.SingleTone, QtCore.SIGNAL("clicked()"), self.phase_profiles.show)
        QtCore.QObject.connect(self.SingleTone, QtCore.SIGNAL("clicked()"), self.frequency_profiles.show)
        QtCore.QMetaObject.connectSlotsByName(DDSDialog)

    def retranslateUi(self, DDSDialog):
        DDSDialog.setWindowTitle(QtGui.QApplication.translate("DDSDialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.exitButton.setText(QtGui.QApplication.translate("DDSDialog", "Done", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("DDSDialog", "DDS serial number:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("DDSDialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("DDSDialog", "P3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("DDSDialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("DDSDialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("DDSDialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("DDSDialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("DDSDialog", "P2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("DDSDialog", "P1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("DDSDialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("DDSDialog", "P0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("DDSDialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("DDSDialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("DDSDialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("DDSDialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("DDSDialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("DDSDialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("DDSDialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("DDSDialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("DDSDialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("DDSDialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("DDSDialog", "RF0 Phase/Deg ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("DDSDialog", "RF1 Phase/Deg ", None, QtGui.QApplication.UnicodeUTF8))
        self.PhaseModulation.setText(QtGui.QApplication.translate("DDSDialog", "Phase Modulation", None, QtGui.QApplication.UnicodeUTF8))
        self.SingleTone.setText(QtGui.QApplication.translate("DDSDialog", "Single Tone", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("DDSDialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("DDSDialog", "P3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("DDSDialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("DDSDialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("DDSDialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("DDSDialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("DDSDialog", "P2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("DDSDialog", "P1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("DDSDialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("DDSDialog", "P0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_44.setText(QtGui.QApplication.translate("DDSDialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_45.setText(QtGui.QApplication.translate("DDSDialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_46.setText(QtGui.QApplication.translate("DDSDialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("DDSDialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_47.setText(QtGui.QApplication.translate("DDSDialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_48.setText(QtGui.QApplication.translate("DDSDialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_49.setText(QtGui.QApplication.translate("DDSDialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_50.setText(QtGui.QApplication.translate("DDSDialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_51.setText(QtGui.QApplication.translate("DDSDialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_52.setText(QtGui.QApplication.translate("DDSDialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_53.setText(QtGui.QApplication.translate("DDSDialog", "RF0 Frequency (Hz)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_54.setText(QtGui.QApplication.translate("DDSDialog", "RF1 Frequency (Hz)", None, QtGui.QApplication.UnicodeUTF8))
        self.FrequencyModulation.setText(QtGui.QApplication.translate("DDSDialog", "Frequency Modulation", None, QtGui.QApplication.UnicodeUTF8))

