# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainion_hq.ui'
#
# Created: Fri Apr 25 14:28:16 2014
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1048, 560)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 0, 731, 511))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet(_fromUtf8(""))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.scanTab = QtGui.QWidget()
        self.scanTab.setStyleSheet(_fromUtf8("background-color: rgb(166, 255, 253);"))
        self.scanTab.setObjectName(_fromUtf8("scanTab"))
        self.progressBar = QtGui.QProgressBar(self.scanTab)
        self.progressBar.setGeometry(QtCore.QRect(40, 370, 651, 23))
        self.progressBar.setMaximum(5)
        self.progressBar.setProperty(_fromUtf8("value"), 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.simple_scan_qwt_plot = Qwt5.QwtPlot(self.scanTab)
        self.simple_scan_qwt_plot.setGeometry(QtCore.QRect(30, 30, 651, 321))
        self.simple_scan_qwt_plot.setObjectName(_fromUtf8("simple_scan_qwt_plot"))
        self.reset_scan_Button = QtGui.QPushButton(self.scanTab)
        self.reset_scan_Button.setGeometry(QtCore.QRect(40, 420, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.reset_scan_Button.setFont(font)
        self.reset_scan_Button.setObjectName(_fromUtf8("reset_scan_Button"))
        self.averageNumber = QtGui.QLCDNumber(self.scanTab)
        self.averageNumber.setGeometry(QtCore.QRect(520, 410, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.averageNumber.setFont(font)
        self.averageNumber.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 127);"))
        self.averageNumber.setSmallDecimalPoint(False)
        self.averageNumber.setNumDigits(6)
        self.averageNumber.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.averageNumber.setProperty(_fromUtf8("value"), 0.0)
        self.averageNumber.setObjectName(_fromUtf8("averageNumber"))
        self.label_19 = QtGui.QLabel(self.scanTab)
        self.label_19.setGeometry(QtCore.QRect(390, 410, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.scan_num_exp_label = QtGui.QLabel(self.scanTab)
        self.scan_num_exp_label.setGeometry(QtCore.QRect(360, 430, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.scan_num_exp_label.setFont(font)
        self.scan_num_exp_label.setObjectName(_fromUtf8("scan_num_exp_label"))
        self.tabWidget.addTab(self.scanTab, _fromUtf8(""))
        self.freqScan = QtGui.QWidget()
        self.freqScan.setStyleSheet(_fromUtf8("background-color: rgb(185, 255, 164);"))
        self.freqScan.setObjectName(_fromUtf8("freqScan"))
        self.freq_scan_qwt_plot = Qwt5.QwtPlot(self.freqScan)
        self.freq_scan_qwt_plot.setGeometry(QtCore.QRect(30, 20, 661, 351))
        self.freq_scan_qwt_plot.setObjectName(_fromUtf8("freq_scan_qwt_plot"))
        self.freq_description = QtGui.QLabel(self.freqScan)
        self.freq_description.setGeometry(QtCore.QRect(150, 440, 371, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.freq_description.setFont(font)
        self.freq_description.setObjectName(_fromUtf8("freq_description"))
        self.freq_stop = QtGui.QDoubleSpinBox(self.freqScan)
        self.freq_stop.setGeometry(QtCore.QRect(413, 418, 101, 20))
        self.freq_stop.setStyleSheet(_fromUtf8("font: 11pt \"MS Shell Dlg 2\";"))
        self.freq_stop.setDecimals(6)
        self.freq_stop.setMinimum(0.1)
        self.freq_stop.setMaximum(9999999.99)
        self.freq_stop.setProperty(_fromUtf8("value"), 1.01)
        self.freq_stop.setObjectName(_fromUtf8("freq_stop"))
        self.freq_step = QtGui.QDoubleSpinBox(self.freqScan)
        self.freq_step.setGeometry(QtCore.QRect(516, 418, 91, 20))
        self.freq_step.setStyleSheet(_fromUtf8("font: 11pt \"MS Shell Dlg 2\";"))
        self.freq_step.setDecimals(6)
        self.freq_step.setMinimum(-999999.999)
        self.freq_step.setMaximum(999999.999)
        self.freq_step.setSingleStep(0.001)
        self.freq_step.setProperty(_fromUtf8("value"), 0.001)
        self.freq_step.setObjectName(_fromUtf8("freq_step"))
        self.freq_start = QtGui.QDoubleSpinBox(self.freqScan)
        self.freq_start.setGeometry(QtCore.QRect(311, 418, 101, 20))
        self.freq_start.setStyleSheet(_fromUtf8("font: 11pt \"MS Shell Dlg 2\";"))
        self.freq_start.setDecimals(6)
        self.freq_start.setMinimum(0.1)
        self.freq_start.setMaximum(999999.99)
        self.freq_start.setObjectName(_fromUtf8("freq_start"))
        self.label_13 = QtGui.QLabel(self.freqScan)
        self.label_13.setGeometry(QtCore.QRect(318, 380, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.freqScan)
        self.label_14.setGeometry(QtCore.QRect(430, 380, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.freqScan)
        self.label_15.setGeometry(QtCore.QRect(540, 380, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.freq_current = QtGui.QLabel(self.freqScan)
        self.freq_current.setGeometry(QtCore.QRect(610, 460, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.freq_current.setFont(font)
        self.freq_current.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.freq_current.setObjectName(_fromUtf8("freq_current"))
        self.freq_device = QtGui.QComboBox(self.freqScan)
        self.freq_device.setGeometry(QtCore.QRect(28, 418, 121, 21))
        self.freq_device.setStyleSheet(_fromUtf8("font: 10pt \"MS Shell Dlg 2\";"))
        self.freq_device.setObjectName(_fromUtf8("freq_device"))
        self.label_12 = QtGui.QLabel(self.freqScan)
        self.label_12.setGeometry(QtCore.QRect(630, 380, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.freq_default = QtGui.QDoubleSpinBox(self.freqScan)
        self.freq_default.setGeometry(QtCore.QRect(610, 418, 101, 20))
        self.freq_default.setStyleSheet(_fromUtf8("font: 11pt \"MS Shell Dlg 2\";"))
        self.freq_default.setDecimals(6)
        self.freq_default.setMinimum(0.02)
        self.freq_default.setMaximum(999999.99)
        self.freq_default.setSingleStep(1.0)
        self.freq_default.setObjectName(_fromUtf8("freq_default"))
        self.label_17 = QtGui.QLabel(self.freqScan)
        self.label_17.setGeometry(QtCore.QRect(20, 440, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_10 = QtGui.QLabel(self.freqScan)
        self.label_10.setGeometry(QtCore.QRect(30, 373, 51, 28))
        self.label_10.setMinimumSize(QtCore.QSize(0, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_18 = QtGui.QLabel(self.freqScan)
        self.label_18.setGeometry(QtCore.QRect(150, 379, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.freq_property = QtGui.QComboBox(self.freqScan)
        self.freq_property.setGeometry(QtCore.QRect(148, 418, 161, 21))
        self.freq_property.setStyleSheet(_fromUtf8("font: 10pt \"MS Shell Dlg 2\";"))
        self.freq_property.setObjectName(_fromUtf8("freq_property"))
        self.freq_device_2 = QtGui.QComboBox(self.freqScan)
        self.freq_device_2.setGeometry(QtCore.QRect(28, 398, 121, 21))
        self.freq_device_2.setStyleSheet(_fromUtf8("font: 10pt \"MS Shell Dlg 2\";"))
        self.freq_device_2.setObjectName(_fromUtf8("freq_device_2"))
        self.label_16 = QtGui.QLabel(self.freqScan)
        self.label_16.setGeometry(QtCore.QRect(530, 440, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.freq_stop_2 = QtGui.QDoubleSpinBox(self.freqScan)
        self.freq_stop_2.setEnabled(False)
        self.freq_stop_2.setGeometry(QtCore.QRect(413, 398, 101, 20))
        self.freq_stop_2.setStyleSheet(_fromUtf8("font: 11pt \"MS Shell Dlg 2\";"))
        self.freq_stop_2.setDecimals(6)
        self.freq_stop_2.setMinimum(0.1)
        self.freq_stop_2.setMaximum(9999999.99)
        self.freq_stop_2.setProperty(_fromUtf8("value"), 1.01)
        self.freq_stop_2.setObjectName(_fromUtf8("freq_stop_2"))
        self.freq_step_2 = QtGui.QDoubleSpinBox(self.freqScan)
        self.freq_step_2.setGeometry(QtCore.QRect(516, 398, 91, 20))
        self.freq_step_2.setStyleSheet(_fromUtf8("font: 11pt \"MS Shell Dlg 2\";"))
        self.freq_step_2.setDecimals(6)
        self.freq_step_2.setMinimum(-999999.999)
        self.freq_step_2.setMaximum(999999.999)
        self.freq_step_2.setSingleStep(0.001)
        self.freq_step_2.setProperty(_fromUtf8("value"), 0.001)
        self.freq_step_2.setObjectName(_fromUtf8("freq_step_2"))
        self.freq_default_2 = QtGui.QDoubleSpinBox(self.freqScan)
        self.freq_default_2.setGeometry(QtCore.QRect(610, 398, 101, 20))
        self.freq_default_2.setStyleSheet(_fromUtf8("font: 11pt \"MS Shell Dlg 2\";"))
        self.freq_default_2.setDecimals(6)
        self.freq_default_2.setMaximum(999999.99)
        self.freq_default_2.setSingleStep(1.0)
        self.freq_default_2.setObjectName(_fromUtf8("freq_default_2"))
        self.freq_property_2 = QtGui.QComboBox(self.freqScan)
        self.freq_property_2.setGeometry(QtCore.QRect(148, 398, 161, 21))
        self.freq_property_2.setStyleSheet(_fromUtf8("font: 10pt \"MS Shell Dlg 2\";"))
        self.freq_property_2.setObjectName(_fromUtf8("freq_property_2"))
        self.freq_start_2 = QtGui.QDoubleSpinBox(self.freqScan)
        self.freq_start_2.setGeometry(QtCore.QRect(311, 398, 101, 20))
        self.freq_start_2.setStyleSheet(_fromUtf8("font: 11pt \"MS Shell Dlg 2\";"))
        self.freq_start_2.setDecimals(6)
        self.freq_start_2.setMinimum(0.1)
        self.freq_start_2.setMaximum(999999.99)
        self.freq_start_2.setObjectName(_fromUtf8("freq_start_2"))
        self.freq_checkBox_2 = QtGui.QCheckBox(self.freqScan)
        self.freq_checkBox_2.setEnabled(True)
        self.freq_checkBox_2.setGeometry(QtCore.QRect(10, 398, 16, 20))
        self.freq_checkBox_2.setText(_fromUtf8(""))
        self.freq_checkBox_2.setObjectName(_fromUtf8("freq_checkBox_2"))
        self.freq_current_2 = QtGui.QLabel(self.freqScan)
        self.freq_current_2.setGeometry(QtCore.QRect(610, 441, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.freq_current_2.setFont(font)
        self.freq_current_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.freq_current_2.setObjectName(_fromUtf8("freq_current_2"))
        self.tabWidget.addTab(self.freqScan, _fromUtf8(""))
        self.timeScan = QtGui.QWidget()
        self.timeScan.setStyleSheet(_fromUtf8("background-color: rgb(255, 170, 255);"))
        self.timeScan.setObjectName(_fromUtf8("timeScan"))
        self.delay_scan_qwt_plot = Qwt5.QwtPlot(self.timeScan)
        self.delay_scan_qwt_plot.setGeometry(QtCore.QRect(40, 30, 641, 321))
        self.delay_scan_qwt_plot.setObjectName(_fromUtf8("delay_scan_qwt_plot"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.timeScan)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(40, 370, 641, 61))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.delay_start = QtGui.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.delay_start.setStyleSheet(_fromUtf8("font: 12pt \"MS Shell Dlg 2\";"))
        self.delay_start.setMinimum(0.1)
        self.delay_start.setMaximum(999999.99)
        self.delay_start.setObjectName(_fromUtf8("delay_start"))
        self.gridLayout_2.addWidget(self.delay_start, 1, 2, 1, 1)
        self.delay_stop = QtGui.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.delay_stop.setStyleSheet(_fromUtf8("font: 12pt \"MS Shell Dlg 2\";"))
        self.delay_stop.setMinimum(0.1)
        self.delay_stop.setMaximum(9999999.99)
        self.delay_stop.setProperty(_fromUtf8("value"), 10000.0)
        self.delay_stop.setObjectName(_fromUtf8("delay_stop"))
        self.gridLayout_2.addWidget(self.delay_stop, 1, 3, 1, 1)
        self.delay_step = QtGui.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.delay_step.setStyleSheet(_fromUtf8("font: 12pt \"MS Shell Dlg 2\";"))
        self.delay_step.setMinimum(0.02)
        self.delay_step.setMaximum(999999.99)
        self.delay_step.setSingleStep(1.0)
        self.delay_step.setProperty(_fromUtf8("value"), 20.0)
        self.delay_step.setObjectName(_fromUtf8("delay_step"))
        self.gridLayout_2.addWidget(self.delay_step, 1, 4, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 0, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 0, 3, 1, 1)
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 0, 4, 1, 1)
        self.current_delay = QtGui.QLabel(self.gridLayoutWidget_2)
        self.current_delay.setStyleSheet(_fromUtf8("font: 12pt \"MS Shell Dlg 2\";"))
        self.current_delay.setObjectName(_fromUtf8("current_delay"))
        self.gridLayout_2.addWidget(self.current_delay, 1, 5, 1, 1)
        self.label_11 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 0, 5, 1, 1)
        self.delay_chapter_line = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.delay_chapter_line.setEnabled(True)
        self.delay_chapter_line.setStyleSheet(_fromUtf8("font: 10pt \"MS Shell Dlg 2\";"))
        self.delay_chapter_line.setReadOnly(True)
        self.delay_chapter_line.setObjectName(_fromUtf8("delay_chapter_line"))
        self.gridLayout_2.addWidget(self.delay_chapter_line, 1, 0, 1, 1)
        self.delay_line_number = QtGui.QLabel(self.gridLayoutWidget_2)
        self.delay_line_number.setStyleSheet(_fromUtf8("font: 12pt \"MS Shell Dlg 2\";"))
        self.delay_line_number.setObjectName(_fromUtf8("delay_line_number"))
        self.gridLayout_2.addWidget(self.delay_line_number, 1, 1, 1, 1)
        self.tabWidget.addTab(self.timeScan, _fromUtf8(""))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(760, 100, 71, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.lcdNumber = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(910, 393, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 127);"))
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(800, 400, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(760, 320, 151, 56))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.thresholdBox = QtGui.QSpinBox(self.gridLayoutWidget)
        self.thresholdBox.setProperty(_fromUtf8("value"), 2)
        self.thresholdBox.setObjectName(_fromUtf8("thresholdBox"))
        self.gridLayout.addWidget(self.thresholdBox, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.repetitionBox = QtGui.QSpinBox(self.gridLayoutWidget)
        self.repetitionBox.setMinimum(1)
        self.repetitionBox.setMaximum(10000)
        self.repetitionBox.setProperty(_fromUtf8("value"), 100)
        self.repetitionBox.setObjectName(_fromUtf8("repetitionBox"))
        self.gridLayout.addWidget(self.repetitionBox, 0, 1, 1, 1)
        self.histrogram_qwt_plot = Qwt5.QwtPlot(self.centralwidget)
        self.histrogram_qwt_plot.setGeometry(QtCore.QRect(760, 120, 271, 191))
        self.histrogram_qwt_plot.setObjectName(_fromUtf8("histrogram_qwt_plot"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(760, 437, 261, 71))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.scan_Button = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.scan_Button.setFont(font)
        self.scan_Button.setStyleSheet(_fromUtf8("background-color: rgb(255, 85, 0);"))
        self.scan_Button.setCheckable(True)
        self.scan_Button.setObjectName(_fromUtf8("scan_Button"))
        self.gridLayout_4.addWidget(self.scan_Button, 0, 0, 1, 1)
        self.pause_Button = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pause_Button.setFont(font)
        self.pause_Button.setCheckable(True)
        self.pause_Button.setObjectName(_fromUtf8("pause_Button"))
        self.gridLayout_4.addWidget(self.pause_Button, 0, 1, 1, 1)
        self.scan_once = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.scan_once.setFont(font)
        self.scan_once.setChecked(True)
        self.scan_once.setObjectName(_fromUtf8("scan_once"))
        self.gridLayout_4.addWidget(self.scan_once, 1, 0, 1, 1)
        self.scan_method = QtGui.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.scan_method.setFont(font)
        self.scan_method.setObjectName(_fromUtf8("scan_method"))
        self.gridLayout_4.addWidget(self.scan_method, 1, 1, 1, 1)
        self.gridLayoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(772, 30, 271, 71))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setHorizontalSpacing(1)
        self.gridLayout_3.setVerticalSpacing(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.crystallize_button0 = QtGui.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.crystallize_button0.setFont(font)
        self.crystallize_button0.setObjectName(_fromUtf8("crystallize_button0"))
        self.gridLayout_3.addWidget(self.crystallize_button0, 0, 0, 1, 1)
        self.crystallize_doubleSpinBox1 = QtGui.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.crystallize_doubleSpinBox1.setStyleSheet(_fromUtf8("font: 12pt \"MS Shell Dlg 2\";"))
        self.crystallize_doubleSpinBox1.setDecimals(2)
        self.crystallize_doubleSpinBox1.setMaximum(999999.99)
        self.crystallize_doubleSpinBox1.setProperty(_fromUtf8("value"), 65.0)
        self.crystallize_doubleSpinBox1.setObjectName(_fromUtf8("crystallize_doubleSpinBox1"))
        self.gridLayout_3.addWidget(self.crystallize_doubleSpinBox1, 2, 1, 1, 1)
        self.crystallize_button1 = QtGui.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.crystallize_button1.setFont(font)
        self.crystallize_button1.setObjectName(_fromUtf8("crystallize_button1"))
        self.gridLayout_3.addWidget(self.crystallize_button1, 2, 0, 1, 1)
        self.crystallize_doubleSpinBox0 = QtGui.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.crystallize_doubleSpinBox0.setStyleSheet(_fromUtf8("font: 12pt \"MS Shell Dlg 2\";"))
        self.crystallize_doubleSpinBox0.setMaximum(999999.99)
        self.crystallize_doubleSpinBox0.setProperty(_fromUtf8("value"), 155.0)
        self.crystallize_doubleSpinBox0.setObjectName(_fromUtf8("crystallize_doubleSpinBox0"))
        self.gridLayout_3.addWidget(self.crystallize_doubleSpinBox0, 0, 1, 1, 1)
        self.apply_threshold = QtGui.QCheckBox(self.centralwidget)
        self.apply_threshold.setGeometry(QtCore.QRect(920, 330, 71, 41))
        self.apply_threshold.setObjectName(_fromUtf8("apply_threshold"))
        self.Lower_Trap_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.Lower_Trap_checkBox.setGeometry(QtCore.QRect(780, 10, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Lower_Trap_checkBox.setFont(font)
        self.Lower_Trap_checkBox.setObjectName(_fromUtf8("Lower_Trap_checkBox"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1048, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuFit = QtGui.QMenu(self.menubar)
        self.menuFit.setObjectName(_fromUtf8("menuFit"))
        self.menuPhase_Modulation = QtGui.QMenu(self.menubar)
        self.menuPhase_Modulation.setTearOffEnabled(False)
        self.menuPhase_Modulation.setObjectName(_fromUtf8("menuPhase_Modulation"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionSave = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.actionSave.setFont(font)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionSave_Histogram = QtGui.QAction(MainWindow)
        self.actionSave_Histogram.setObjectName(_fromUtf8("actionSave_Histogram"))
        self.actionFrequency_Fit = QtGui.QAction(MainWindow)
        self.actionFrequency_Fit.setObjectName(_fromUtf8("actionFrequency_Fit"))
        self.actionSine_Fit = QtGui.QAction(MainWindow)
        self.actionSine_Fit.setObjectName(_fromUtf8("actionSine_Fit"))
        self.actionControl_Window = QtGui.QAction(MainWindow)
        self.actionControl_Window.setObjectName(_fromUtf8("actionControl_Window"))
        self.LoadSettings = QtGui.QAction(MainWindow)
        self.LoadSettings.setObjectName(_fromUtf8("LoadSettings"))
        self.SaveSettings = QtGui.QAction(MainWindow)
        self.SaveSettings.setObjectName(_fromUtf8("SaveSettings"))
        self.actionCounters = QtGui.QAction(MainWindow)
        self.actionCounters.setObjectName(_fromUtf8("actionCounters"))
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_Histogram)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuFit.addAction(self.actionFrequency_Fit)
        self.menuFit.addAction(self.actionSine_Fit)
        self.menuPhase_Modulation.addAction(self.actionControl_Window)
        self.menuSettings.addAction(self.LoadSettings)
        self.menuSettings.addAction(self.SaveSettings)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.actionCounters)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuFit.menuAction())
        self.menubar.addAction(self.menuPhase_Modulation.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.reset_scan_Button.setText(QtGui.QApplication.translate("MainWindow", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Average value", None, QtGui.QApplication.UnicodeUTF8))
        self.scan_num_exp_label.setText(QtGui.QApplication.translate("MainWindow", "over 0 expeiments ", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.scanTab), QtGui.QApplication.translate("MainWindow", "Alignment Scan", None, QtGui.QApplication.UnicodeUTF8))
        self.freq_description.setText(QtGui.QApplication.translate("MainWindow", "Unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Start ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Stop ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Step", None, QtGui.QApplication.UnicodeUTF8))
        self.freq_current.setText(QtGui.QApplication.translate("MainWindow", "0.10", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Default ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Device", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Property", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Current", None, QtGui.QApplication.UnicodeUTF8))
        self.freq_current_2.setText(QtGui.QApplication.translate("MainWindow", "0.10", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.freqScan), QtGui.QApplication.translate("MainWindow", "Frequency Scan", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Chapter", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Line", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Start delay", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Stop delay", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Step", None, QtGui.QApplication.UnicodeUTF8))
        self.current_delay.setText(QtGui.QApplication.translate("MainWindow", "0.10", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Current delay", None, QtGui.QApplication.UnicodeUTF8))
        self.delay_line_number.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.timeScan), QtGui.QApplication.translate("MainWindow", "Delay Scan", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Histogram", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Current Value:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Threshold", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">No. of expts</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.scan_Button.setText(QtGui.QApplication.translate("MainWindow", "Scan", None, QtGui.QApplication.UnicodeUTF8))
        self.pause_Button.setText(QtGui.QApplication.translate("MainWindow", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.scan_once.setText(QtGui.QApplication.translate("MainWindow", "Scan Once", None, QtGui.QApplication.UnicodeUTF8))
        self.crystallize_button0.setText(QtGui.QApplication.translate("MainWindow", "Need to crystallize", None, QtGui.QApplication.UnicodeUTF8))
        self.crystallize_button1.setText(QtGui.QApplication.translate("MainWindow", "Crystallized", None, QtGui.QApplication.UnicodeUTF8))
        self.apply_threshold.setText(QtGui.QApplication.translate("MainWindow", "Apply\n"
"Threshold", None, QtGui.QApplication.UnicodeUTF8))
        self.Lower_Trap_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Lower Trap", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFit.setTitle(QtGui.QApplication.translate("MainWindow", "Fit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPhase_Modulation.setTitle(QtGui.QApplication.translate("MainWindow", "Phase Modulation", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSettings.setTitle(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Histogram.setText(QtGui.QApplication.translate("MainWindow", "Save with Histogram", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFrequency_Fit.setText(QtGui.QApplication.translate("MainWindow", "Frequency Fit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSine_Fit.setText(QtGui.QApplication.translate("MainWindow", "Sine Fit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionControl_Window.setText(QtGui.QApplication.translate("MainWindow", "Control Window...", None, QtGui.QApplication.UnicodeUTF8))
        self.LoadSettings.setText(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.SaveSettings.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCounters.setText(QtGui.QApplication.translate("MainWindow", "Counters", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import Qwt5
