# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_coil_ui.ui'
#
# Created: Thu Dec 18 18:52:44 2014
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1048, 560)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 0, 731, 511))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.scanTab = QtGui.QWidget()
        self.scanTab.setStyleSheet("background-color: rgb(166, 255, 253);")
        self.scanTab.setObjectName("scanTab")
        self.progressBar = QtGui.QProgressBar(self.scanTab)
        self.progressBar.setGeometry(QtCore.QRect(40, 370, 651, 23))
        self.progressBar.setMaximum(5)
        self.progressBar.setProperty("value", QtCore.QVariant(0))
        self.progressBar.setObjectName("progressBar")
        self.simple_scan_qwt_plot = Qwt5.QwtPlot(self.scanTab)
        self.simple_scan_qwt_plot.setGeometry(QtCore.QRect(30, 30, 651, 321))
        self.simple_scan_qwt_plot.setObjectName("simple_scan_qwt_plot")
        self.reset_scan_Button = QtGui.QPushButton(self.scanTab)
        self.reset_scan_Button.setGeometry(QtCore.QRect(40, 420, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.reset_scan_Button.setFont(font)
        self.reset_scan_Button.setObjectName("reset_scan_Button")
        self.averageNumber = QtGui.QLCDNumber(self.scanTab)
        self.averageNumber.setGeometry(QtCore.QRect(520, 410, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.averageNumber.setFont(font)
        self.averageNumber.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.averageNumber.setSmallDecimalPoint(False)
        self.averageNumber.setNumDigits(6)
        self.averageNumber.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.averageNumber.setProperty("value", QtCore.QVariant(0.0))
        self.averageNumber.setObjectName("averageNumber")
        self.label_19 = QtGui.QLabel(self.scanTab)
        self.label_19.setGeometry(QtCore.QRect(390, 410, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.scan_num_exp_label = QtGui.QLabel(self.scanTab)
        self.scan_num_exp_label.setGeometry(QtCore.QRect(360, 430, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.scan_num_exp_label.setFont(font)
        self.scan_num_exp_label.setObjectName("scan_num_exp_label")
        self.tabWidget.addTab(self.scanTab, "")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(800, 400, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(760, 437, 261, 71))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_4 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.scan_Button = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.scan_Button.setFont(font)
        self.scan_Button.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.scan_Button.setCheckable(True)
        self.scan_Button.setObjectName("scan_Button")
        self.gridLayout_4.addWidget(self.scan_Button, 0, 0, 1, 1)
        self.pause_Button = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pause_Button.setFont(font)
        self.pause_Button.setCheckable(True)
        self.pause_Button.setObjectName("pause_Button")
        self.gridLayout_4.addWidget(self.pause_Button, 0, 1, 1, 1)
        self.current_label = QtGui.QLabel(self.centralwidget)
        self.current_label.setGeometry(QtCore.QRect(910, 400, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.current_label.setFont(font)
        self.current_label.setObjectName("current_label")
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(920, 370, 75, 23))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1048, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuFit = QtGui.QMenu(self.menubar)
        self.menuFit.setObjectName("menuFit")
        self.menuPhase_Modulation = QtGui.QMenu(self.menubar)
        self.menuPhase_Modulation.setTearOffEnabled(False)
        self.menuPhase_Modulation.setObjectName("menuPhase_Modulation")
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSave = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.actionSave.setFont(font)
        self.actionSave.setObjectName("actionSave")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSave_Histogram = QtGui.QAction(MainWindow)
        self.actionSave_Histogram.setObjectName("actionSave_Histogram")
        self.actionFrequency_Fit = QtGui.QAction(MainWindow)
        self.actionFrequency_Fit.setObjectName("actionFrequency_Fit")
        self.actionSine_Fit = QtGui.QAction(MainWindow)
        self.actionSine_Fit.setObjectName("actionSine_Fit")
        self.actionControl_Window = QtGui.QAction(MainWindow)
        self.actionControl_Window.setObjectName("actionControl_Window")
        self.LoadSettings = QtGui.QAction(MainWindow)
        self.LoadSettings.setObjectName("LoadSettings")
        self.SaveSettings = QtGui.QAction(MainWindow)
        self.SaveSettings.setObjectName("SaveSettings")
        self.actionCounters = QtGui.QAction(MainWindow)
        self.actionCounters.setObjectName("actionCounters")
        self.actionRamsey_Fit = QtGui.QAction(MainWindow)
        self.actionRamsey_Fit.setObjectName("actionRamsey_Fit")
        self.actionCounters_Plot = QtGui.QAction(MainWindow)
        self.actionCounters_Plot.setObjectName("actionCounters_Plot")
        self.actionSet_Scan_File = QtGui.QAction(MainWindow)
        self.actionSet_Scan_File.setObjectName("actionSet_Scan_File")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_Histogram)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuFit.addAction(self.actionFrequency_Fit)
        self.menuFit.addAction(self.actionSine_Fit)
        self.menuFit.addAction(self.actionRamsey_Fit)
        self.menuPhase_Modulation.addAction(self.actionControl_Window)
        self.menuSettings.addAction(self.LoadSettings)
        self.menuSettings.addAction(self.SaveSettings)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.actionCounters)
        self.menuSettings.addAction(self.actionCounters_Plot)
        self.menuSettings.addAction(self.actionSet_Scan_File)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuFit.menuAction())
        self.menubar.addAction(self.menuPhase_Modulation.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.reset_scan_Button.setText(QtGui.QApplication.translate("MainWindow", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Average value", None, QtGui.QApplication.UnicodeUTF8))
        self.scan_num_exp_label.setText(QtGui.QApplication.translate("MainWindow", "over 0 expeiments ", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.scanTab), QtGui.QApplication.translate("MainWindow", "Alignment Scan", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Current Value:", None, QtGui.QApplication.UnicodeUTF8))
        self.scan_Button.setText(QtGui.QApplication.translate("MainWindow", "Get Data", None, QtGui.QApplication.UnicodeUTF8))
        self.pause_Button.setText(QtGui.QApplication.translate("MainWindow", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.current_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Get Now!", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFit.setTitle(QtGui.QApplication.translate("MainWindow", "Fit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPhase_Modulation.setTitle(QtGui.QApplication.translate("MainWindow", "Modulation", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSettings.setTitle(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Histogram.setText(QtGui.QApplication.translate("MainWindow", "Save with Histogram", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFrequency_Fit.setText(QtGui.QApplication.translate("MainWindow", "Frequency Fit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSine_Fit.setText(QtGui.QApplication.translate("MainWindow", "Sine Fit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionControl_Window.setText(QtGui.QApplication.translate("MainWindow", "Control Window...", None, QtGui.QApplication.UnicodeUTF8))
        self.LoadSettings.setText(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.SaveSettings.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCounters.setText(QtGui.QApplication.translate("MainWindow", "Counters", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRamsey_Fit.setText(QtGui.QApplication.translate("MainWindow", "Ramsey Fit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCounters_Plot.setText(QtGui.QApplication.translate("MainWindow", "Counter Plots", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSet_Scan_File.setText(QtGui.QApplication.translate("MainWindow", "Set Scan File", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import Qwt5
