# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'antiX_fit_ui.ui'
#
# Created: Fri Jun 17 09:54:12 2016
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_AntiX_Dialog(object):
    def setupUi(self, AntiX_Dialog):
        AntiX_Dialog.setObjectName("AntiX_Dialog")
        AntiX_Dialog.resize(318, 330)
        self.formLayoutWidget = QtGui.QWidget(AntiX_Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(80, 70, 208, 224))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setObjectName("formLayout")
        self.aSpinBox = QtGui.QDoubleSpinBox(self.formLayoutWidget)
        self.aSpinBox.setMaximum(999.99)
        self.aSpinBox.setObjectName("aSpinBox")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.aSpinBox)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.b1SpinBox = QtGui.QDoubleSpinBox(self.formLayoutWidget)
        self.b1SpinBox.setMaximum(99999.99)
        self.b1SpinBox.setProperty("value", QtCore.QVariant(0.5))
        self.b1SpinBox.setObjectName("b1SpinBox")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.b1SpinBox)
        self.Tpi1SpinBox = QtGui.QDoubleSpinBox(self.formLayoutWidget)
        self.Tpi1SpinBox.setMaximum(99999.99)
        self.Tpi1SpinBox.setProperty("value", QtCore.QVariant(10.0))
        self.Tpi1SpinBox.setObjectName("Tpi1SpinBox")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.Tpi1SpinBox)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_4)
        self.TSpinBox = QtGui.QDoubleSpinBox(self.formLayoutWidget)
        self.TSpinBox.setMaximum(99999.99)
        self.TSpinBox.setProperty("value", QtCore.QVariant(10.0))
        self.TSpinBox.setObjectName("TSpinBox")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.TSpinBox)
        self.label_5 = QtGui.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_5)
        self.freq1SpinBox = QtGui.QDoubleSpinBox(self.formLayoutWidget)
        self.freq1SpinBox.setDecimals(6)
        self.freq1SpinBox.setMaximum(99999.99)
        self.freq1SpinBox.setSingleStep(0.1)
        self.freq1SpinBox.setProperty("value", QtCore.QVariant(100.0))
        self.freq1SpinBox.setObjectName("freq1SpinBox")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.freq1SpinBox)
        self.label_3 = QtGui.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_3)
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.label_6 = QtGui.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_6)
        self.b2SpinBox = QtGui.QDoubleSpinBox(self.formLayoutWidget)
        self.b2SpinBox.setMaximum(99999.99)
        self.b2SpinBox.setProperty("value", QtCore.QVariant(0.5))
        self.b2SpinBox.setObjectName("b2SpinBox")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.b2SpinBox)
        self.label_7 = QtGui.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_7)
        self.Tpi2SpinBox = QtGui.QDoubleSpinBox(self.formLayoutWidget)
        self.Tpi2SpinBox.setMaximum(99999.99)
        self.Tpi2SpinBox.setProperty("value", QtCore.QVariant(10.0))
        self.Tpi2SpinBox.setObjectName("Tpi2SpinBox")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.Tpi2SpinBox)
        self.label_8 = QtGui.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_8)
        self.freq2SpinBox = QtGui.QDoubleSpinBox(self.formLayoutWidget)
        self.freq2SpinBox.setDecimals(6)
        self.freq2SpinBox.setMaximum(99999.99)
        self.freq2SpinBox.setSingleStep(0.1)
        self.freq2SpinBox.setProperty("value", QtCore.QVariant(100.0))
        self.freq2SpinBox.setObjectName("freq2SpinBox")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.freq2SpinBox)
        self.Df_label = QtGui.QLabel(self.formLayoutWidget)
        self.Df_label.setObjectName("Df_label")
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.Df_label)
        self.fitButton = QtGui.QPushButton(AntiX_Dialog)
        self.fitButton.setGeometry(QtCore.QRect(50, 300, 75, 23))
        self.fitButton.setObjectName("fitButton")
        self.doneButton = QtGui.QPushButton(AntiX_Dialog)
        self.doneButton.setGeometry(QtCore.QRect(170, 300, 75, 23))
        self.doneButton.setObjectName("doneButton")
        self.Formula = QtGui.QLabel(AntiX_Dialog)
        self.Formula.setGeometry(QtCore.QRect(20, 10, 260, 20))
        self.Formula.setObjectName("Formula")
        self.FormulaOmega = QtGui.QLabel(AntiX_Dialog)
        self.FormulaOmega.setGeometry(QtCore.QRect(20, 30, 80, 20))
        self.FormulaOmega.setObjectName("FormulaOmega")
        self.FormulaOmega_2 = QtGui.QLabel(AntiX_Dialog)
        self.FormulaOmega_2.setGeometry(QtCore.QRect(20, 50, 240, 20))
        self.FormulaOmega_2.setObjectName("FormulaOmega_2")

        self.retranslateUi(AntiX_Dialog)
        QtCore.QObject.connect(self.doneButton, QtCore.SIGNAL("clicked()"), AntiX_Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(AntiX_Dialog)

    def retranslateUi(self, AntiX_Dialog):
        AntiX_Dialog.setWindowTitle(QtGui.QApplication.translate("AntiX_Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("AntiX_Dialog", "b1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("AntiX_Dialog", "T: Pulse time, us", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("AntiX_Dialog", "f1: Frequency, MHz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("AntiX_Dialog", "Tpi1: Pi time, us", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("AntiX_Dialog", "a", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("AntiX_Dialog", "b2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("AntiX_Dialog", "Tpi2: Pi time, us", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("AntiX_Dialog", "f2: Frequency, MHz", None, QtGui.QApplication.UnicodeUTF8))
        self.Df_label.setText(QtGui.QApplication.translate("AntiX_Dialog", "Df", None, QtGui.QApplication.UnicodeUTF8))
        self.fitButton.setText(QtGui.QApplication.translate("AntiX_Dialog", "Fit", None, QtGui.QApplication.UnicodeUTF8))
        self.fitButton.setShortcut(QtGui.QApplication.translate("AntiX_Dialog", "Ctrl+F", None, QtGui.QApplication.UnicodeUTF8))
        self.doneButton.setText(QtGui.QApplication.translate("AntiX_Dialog", "Done", None, QtGui.QApplication.UnicodeUTF8))
        self.Formula.setText(QtGui.QApplication.translate("AntiX_Dialog", "a+b*( Omega * Sin[Omega1 * T / 2] / Omega1 )^2", None, QtGui.QApplication.UnicodeUTF8))
        self.FormulaOmega.setText(QtGui.QApplication.translate("AntiX_Dialog", "Omega = Pi/Tpi", None, QtGui.QApplication.UnicodeUTF8))
        self.FormulaOmega_2.setText(QtGui.QApplication.translate("AntiX_Dialog", "Omega1 = Sqrt[Omega^2 + (2 Pi (f-f0))^2]", None, QtGui.QApplication.UnicodeUTF8))

