# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CamGUI_mpl_mainwin.ui'
#
# Created: Tue Jan 31 17:32:44 2017
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Cam_mainwin(object):
    def setupUi(self, Cam_mainwin):
        Cam_mainwin.setObjectName("Cam_mainwin")
        Cam_mainwin.resize(779, 599)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Cam_mainwin.sizePolicy().hasHeightForWidth())
        Cam_mainwin.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(Cam_mainwin)
        self.centralwidget.setObjectName("centralwidget")
        self.exitButton = QtGui.QPushButton(self.centralwidget)
        self.exitButton.setGeometry(QtCore.QRect(110, 520, 70, 20))
        self.exitButton.setObjectName("exitButton")
        self.propertycomboBox = QtGui.QComboBox(self.centralwidget)
        self.propertycomboBox.setGeometry(QtCore.QRect(20, 480, 160, 20))
        self.propertycomboBox.setObjectName("propertycomboBox")
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 160, 131))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.xspinBox = QtGui.QSpinBox(self.gridLayoutWidget)
        self.xspinBox.setMinimum(0)
        self.xspinBox.setMaximum(512)
        self.xspinBox.setSingleStep(1)
        self.xspinBox.setProperty("value", QtCore.QVariant(0))
        self.xspinBox.setObjectName("xspinBox")
        self.gridLayout.addWidget(self.xspinBox, 1, 1, 1, 1)
        self.yspinBox = QtGui.QSpinBox(self.gridLayoutWidget)
        self.yspinBox.setMinimum(0)
        self.yspinBox.setMaximum(512)
        self.yspinBox.setSingleStep(1)
        self.yspinBox.setProperty("value", QtCore.QVariant(0))
        self.yspinBox.setObjectName("yspinBox")
        self.gridLayout.addWidget(self.yspinBox, 2, 1, 1, 1)
        self.xSizespinBox = QtGui.QSpinBox(self.gridLayoutWidget)
        self.xSizespinBox.setMinimum(1)
        self.xSizespinBox.setMaximum(512)
        self.xSizespinBox.setSingleStep(4)
        self.xSizespinBox.setProperty("value", QtCore.QVariant(512))
        self.xSizespinBox.setObjectName("xSizespinBox")
        self.gridLayout.addWidget(self.xSizespinBox, 3, 1, 1, 1)
        self.ySizespinBox = QtGui.QSpinBox(self.gridLayoutWidget)
        self.ySizespinBox.setMinimum(1)
        self.ySizespinBox.setMaximum(512)
        self.ySizespinBox.setSingleStep(4)
        self.ySizespinBox.setProperty("value", QtCore.QVariant(512))
        self.ySizespinBox.setObjectName("ySizespinBox")
        self.gridLayout.addWidget(self.ySizespinBox, 4, 1, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.applyROIButton = QtGui.QPushButton(self.gridLayoutWidget)
        self.applyROIButton.setCursor(QtCore.Qt.PointingHandCursor)
        self.applyROIButton.setObjectName("applyROIButton")
        self.gridLayout.addWidget(self.applyROIButton, 0, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(19, 380, 75, 20))
        self.label_8.setObjectName("label_8")
        self.intensityLabel = QtGui.QLabel(self.centralwidget)
        self.intensityLabel.setGeometry(QtCore.QRect(20, 350, 160, 25))
        self.intensityLabel.setObjectName("intensityLabel")
        self.mplwidget = MatplotlibWidget(self.centralwidget)
        self.mplwidget.setGeometry(QtCore.QRect(200, 20, 540, 520))
        self.mplwidget.setObjectName("mplwidget")
        self.gridLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 270, 160, 79))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.POIxspinBox = QtGui.QSpinBox(self.gridLayoutWidget_2)
        self.POIxspinBox.setMinimum(0)
        self.POIxspinBox.setMaximum(512)
        self.POIxspinBox.setProperty("value", QtCore.QVariant(255))
        self.POIxspinBox.setObjectName("POIxspinBox")
        self.gridLayout_2.addWidget(self.POIxspinBox, 1, 1, 1, 1)
        self.POIyspinBox = QtGui.QSpinBox(self.gridLayoutWidget_2)
        self.POIyspinBox.setMinimum(0)
        self.POIyspinBox.setMaximum(512)
        self.POIyspinBox.setProperty("value", QtCore.QVariant(255))
        self.POIyspinBox.setObjectName("POIyspinBox")
        self.gridLayout_2.addWidget(self.POIyspinBox, 2, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.showPOIButton = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.showPOIButton.setObjectName("showPOIButton")
        self.gridLayout_2.addWidget(self.showPOIButton, 0, 1, 1, 1)
        self.propertylabel = QtGui.QLabel(self.centralwidget)
        self.propertylabel.setGeometry(QtCore.QRect(20, 500, 160, 20))
        self.propertylabel.setObjectName("propertylabel")
        self.exposurespinBox = QtGui.QSpinBox(self.centralwidget)
        self.exposurespinBox.setGeometry(QtCore.QRect(100, 380, 77, 20))
        self.exposurespinBox.setMinimum(1)
        self.exposurespinBox.setMaximum(10000)
        self.exposurespinBox.setSingleStep(100)
        self.exposurespinBox.setProperty("value", QtCore.QVariant(500))
        self.exposurespinBox.setObjectName("exposurespinBox")
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 160, 160, 50))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.PMTButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.PMTButton.setObjectName("PMTButton")
        self.horizontalLayout.addWidget(self.PMTButton)
        self.cameraButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.cameraButton.setObjectName("cameraButton")
        self.horizontalLayout.addWidget(self.cameraButton)
        self.fullROIButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.fullROIButton.setObjectName("fullROIButton")
        self.horizontalLayout.addWidget(self.fullROIButton)
        self.ROR_Low_radioButton = QtGui.QRadioButton(self.centralwidget)
        self.ROR_Low_radioButton.setGeometry(QtCore.QRect(100, 410, 70, 18))
        self.ROR_Low_radioButton.setChecked(True)
        self.ROR_Low_radioButton.setObjectName("ROR_Low_radioButton")
        self.ROR_Med_radioButton = QtGui.QRadioButton(self.centralwidget)
        self.ROR_Med_radioButton.setGeometry(QtCore.QRect(100, 430, 70, 18))
        self.ROR_Med_radioButton.setChecked(False)
        self.ROR_Med_radioButton.setObjectName("ROR_Med_radioButton")
        self.ROR_Large_radioButton = QtGui.QRadioButton(self.centralwidget)
        self.ROR_Large_radioButton.setGeometry(QtCore.QRect(100, 450, 70, 18))
        self.ROR_Large_radioButton.setObjectName("ROR_Large_radioButton")
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(20, 420, 75, 40))
        self.label_9.setObjectName("label_9")
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 210, 160, 60))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.snapButton = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.snapButton.setObjectName("snapButton")
        self.horizontalLayout_2.addWidget(self.snapButton)
        self.startButton = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.startButton.setObjectName("startButton")
        self.horizontalLayout_2.addWidget(self.startButton)
        self.resetCamButton = QtGui.QPushButton(self.centralwidget)
        self.resetCamButton.setGeometry(QtCore.QRect(20, 520, 70, 20))
        self.resetCamButton.setObjectName("resetCamButton")
        Cam_mainwin.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Cam_mainwin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 779, 22))
        self.menubar.setObjectName("menubar")
        self.menuFit = QtGui.QMenu(self.menubar)
        self.menuFit.setObjectName("menuFit")
        self.menu_Help = QtGui.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        Cam_mainwin.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Cam_mainwin)
        self.statusbar.setObjectName("statusbar")
        Cam_mainwin.setStatusBar(self.statusbar)
        self.actionGaussian = QtGui.QAction(Cam_mainwin)
        self.actionGaussian.setObjectName("actionGaussian")
        self.actionPrint_Help = QtGui.QAction(Cam_mainwin)
        self.actionPrint_Help.setObjectName("actionPrint_Help")
        self.menuFit.addAction(self.actionGaussian)
        self.menu_Help.addAction(self.actionPrint_Help)
        self.menubar.addAction(self.menuFit.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(Cam_mainwin)
        QtCore.QObject.connect(self.exitButton, QtCore.SIGNAL("clicked()"), Cam_mainwin.close)
        QtCore.QMetaObject.connectSlotsByName(Cam_mainwin)
        Cam_mainwin.setTabOrder(self.applyROIButton, self.xspinBox)
        Cam_mainwin.setTabOrder(self.xspinBox, self.yspinBox)
        Cam_mainwin.setTabOrder(self.yspinBox, self.xSizespinBox)
        Cam_mainwin.setTabOrder(self.xSizespinBox, self.ySizespinBox)
        Cam_mainwin.setTabOrder(self.ySizespinBox, self.PMTButton)
        Cam_mainwin.setTabOrder(self.PMTButton, self.cameraButton)
        Cam_mainwin.setTabOrder(self.cameraButton, self.fullROIButton)
        Cam_mainwin.setTabOrder(self.fullROIButton, self.snapButton)
        Cam_mainwin.setTabOrder(self.snapButton, self.startButton)
        Cam_mainwin.setTabOrder(self.startButton, self.showPOIButton)
        Cam_mainwin.setTabOrder(self.showPOIButton, self.POIxspinBox)
        Cam_mainwin.setTabOrder(self.POIxspinBox, self.POIyspinBox)
        Cam_mainwin.setTabOrder(self.POIyspinBox, self.exposurespinBox)
        Cam_mainwin.setTabOrder(self.exposurespinBox, self.ROR_Med_radioButton)
        Cam_mainwin.setTabOrder(self.ROR_Med_radioButton, self.ROR_Low_radioButton)
        Cam_mainwin.setTabOrder(self.ROR_Low_radioButton, self.ROR_Large_radioButton)
        Cam_mainwin.setTabOrder(self.ROR_Large_radioButton, self.propertycomboBox)
        Cam_mainwin.setTabOrder(self.propertycomboBox, self.resetCamButton)
        Cam_mainwin.setTabOrder(self.resetCamButton, self.exitButton)

    def retranslateUi(self, Cam_mainwin):
        Cam_mainwin.setWindowTitle(QtGui.QApplication.translate("Cam_mainwin", "Camera", None, QtGui.QApplication.UnicodeUTF8))
        self.exitButton.setText(QtGui.QApplication.translate("Cam_mainwin", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Cam_mainwin", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Cam_mainwin", "y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Cam_mainwin", "xSize", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Cam_mainwin", "ySize", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Cam_mainwin", "ROI", None, QtGui.QApplication.UnicodeUTF8))
        self.applyROIButton.setText(QtGui.QApplication.translate("Cam_mainwin", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Cam_mainwin", "Exposure (ms):", None, QtGui.QApplication.UnicodeUTF8))
        self.intensityLabel.setText(QtGui.QApplication.translate("Cam_mainwin", "Intensity: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Cam_mainwin", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Cam_mainwin", "y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Cam_mainwin", "POI", None, QtGui.QApplication.UnicodeUTF8))
        self.showPOIButton.setText(QtGui.QApplication.translate("Cam_mainwin", "Show", None, QtGui.QApplication.UnicodeUTF8))
        self.propertylabel.setText(QtGui.QApplication.translate("Cam_mainwin", "Property", None, QtGui.QApplication.UnicodeUTF8))
        self.PMTButton.setText(QtGui.QApplication.translate("Cam_mainwin", "PMT", None, QtGui.QApplication.UnicodeUTF8))
        self.cameraButton.setText(QtGui.QApplication.translate("Cam_mainwin", "Cam", None, QtGui.QApplication.UnicodeUTF8))
        self.fullROIButton.setText(QtGui.QApplication.translate("Cam_mainwin", "Full", None, QtGui.QApplication.UnicodeUTF8))
        self.ROR_Low_radioButton.setText(QtGui.QApplication.translate("Cam_mainwin", "0.1 MHz", None, QtGui.QApplication.UnicodeUTF8))
        self.ROR_Med_radioButton.setText(QtGui.QApplication.translate("Cam_mainwin", "1 MHz", None, QtGui.QApplication.UnicodeUTF8))
        self.ROR_Large_radioButton.setText(QtGui.QApplication.translate("Cam_mainwin", "5 MHz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Cam_mainwin", "Readout\n"
"Rate (MHz):", None, QtGui.QApplication.UnicodeUTF8))
        self.snapButton.setText(QtGui.QApplication.translate("Cam_mainwin", "Snap", None, QtGui.QApplication.UnicodeUTF8))
        self.startButton.setText(QtGui.QApplication.translate("Cam_mainwin", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.resetCamButton.setText(QtGui.QApplication.translate("Cam_mainwin", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFit.setTitle(QtGui.QApplication.translate("Cam_mainwin", "&Fit", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Help.setTitle(QtGui.QApplication.translate("Cam_mainwin", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGaussian.setText(QtGui.QApplication.translate("Cam_mainwin", "&Gaussian", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrint_Help.setText(QtGui.QApplication.translate("Cam_mainwin", "&Troubleshoot", None, QtGui.QApplication.UnicodeUTF8))

from matplotlibwidget import MatplotlibWidget
