# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'counter_config.ui'
#
# Created: Thu Aug 28 21:54:34 2014
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_CounterConfigWindow(object):
    def setupUi(self, CounterConfigWindow):
        CounterConfigWindow.setObjectName("CounterConfigWindow")
        CounterConfigWindow.resize(798, 488)
        self.centralwidget = QtGui.QWidget(CounterConfigWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.DelayConfigWidget = QtGui.QTabWidget(self.centralwidget)
        self.DelayConfigWidget.setGeometry(QtCore.QRect(40, 20, 681, 411))
        self.DelayConfigWidget.setObjectName("DelayConfigWidget")
        self.counter_tab = QtGui.QWidget()
        self.counter_tab.setObjectName("counter_tab")
        self.gridLayoutWidget = QtGui.QWidget(self.counter_tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 631, 340))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.ch2box = QtGui.QCheckBox(self.gridLayoutWidget)
        self.ch2box.setObjectName("ch2box")
        self.gridLayout.addWidget(self.ch2box, 2, 0, 1, 1)
        self.ch3box = QtGui.QCheckBox(self.gridLayoutWidget)
        self.ch3box.setObjectName("ch3box")
        self.gridLayout.addWidget(self.ch3box, 3, 0, 1, 1)
        self.ch4box = QtGui.QCheckBox(self.gridLayoutWidget)
        self.ch4box.setObjectName("ch4box")
        self.gridLayout.addWidget(self.ch4box, 4, 0, 1, 1)
        self.ch5box = QtGui.QCheckBox(self.gridLayoutWidget)
        self.ch5box.setObjectName("ch5box")
        self.gridLayout.addWidget(self.ch5box, 5, 0, 1, 1)
        self.ch6box = QtGui.QCheckBox(self.gridLayoutWidget)
        self.ch6box.setObjectName("ch6box")
        self.gridLayout.addWidget(self.ch6box, 6, 0, 1, 1)
        self.ch7box = QtGui.QCheckBox(self.gridLayoutWidget)
        self.ch7box.setObjectName("ch7box")
        self.gridLayout.addWidget(self.ch7box, 7, 0, 1, 1)
        self.ch8box = QtGui.QCheckBox(self.gridLayoutWidget)
        self.ch8box.setObjectName("ch8box")
        self.gridLayout.addWidget(self.ch8box, 8, 0, 1, 1)
        self.ch1av = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ch1av.setFont(font)
        self.ch1av.setObjectName("ch1av")
        self.gridLayout.addWidget(self.ch1av, 1, 1, 1, 1)
        self.ch2av = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ch2av.setFont(font)
        self.ch2av.setObjectName("ch2av")
        self.gridLayout.addWidget(self.ch2av, 2, 1, 1, 1)
        self.ch3av = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ch3av.setFont(font)
        self.ch3av.setObjectName("ch3av")
        self.gridLayout.addWidget(self.ch3av, 3, 1, 1, 1)
        self.ch4av = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ch4av.setFont(font)
        self.ch4av.setObjectName("ch4av")
        self.gridLayout.addWidget(self.ch4av, 4, 1, 1, 1)
        self.ch5av = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ch5av.setFont(font)
        self.ch5av.setObjectName("ch5av")
        self.gridLayout.addWidget(self.ch5av, 5, 1, 1, 1)
        self.ch6av = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ch6av.setFont(font)
        self.ch6av.setObjectName("ch6av")
        self.gridLayout.addWidget(self.ch6av, 6, 1, 1, 1)
        self.ch7av = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ch7av.setFont(font)
        self.ch7av.setObjectName("ch7av")
        self.gridLayout.addWidget(self.ch7av, 7, 1, 1, 1)
        self.ch8av = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ch8av.setFont(font)
        self.ch8av.setObjectName("ch8av")
        self.gridLayout.addWidget(self.ch8av, 8, 1, 1, 1)
        self.ch1disp = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ch1disp.setFont(font)
        self.ch1disp.setObjectName("ch1disp")
        self.gridLayout.addWidget(self.ch1disp, 1, 2, 1, 1)
        self.ch2disp = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ch2disp.setFont(font)
        self.ch2disp.setObjectName("ch2disp")
        self.gridLayout.addWidget(self.ch2disp, 2, 2, 1, 1)
        self.ch3disp = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ch3disp.setFont(font)
        self.ch3disp.setObjectName("ch3disp")
        self.gridLayout.addWidget(self.ch3disp, 3, 2, 1, 1)
        self.ch4disp = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ch4disp.setFont(font)
        self.ch4disp.setObjectName("ch4disp")
        self.gridLayout.addWidget(self.ch4disp, 4, 2, 1, 1)
        self.ch5disp = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ch5disp.setFont(font)
        self.ch5disp.setObjectName("ch5disp")
        self.gridLayout.addWidget(self.ch5disp, 5, 2, 1, 1)
        self.ch6disp = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ch6disp.setFont(font)
        self.ch6disp.setObjectName("ch6disp")
        self.gridLayout.addWidget(self.ch6disp, 6, 2, 1, 1)
        self.ch7disp = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ch7disp.setFont(font)
        self.ch7disp.setObjectName("ch7disp")
        self.gridLayout.addWidget(self.ch7disp, 7, 2, 1, 1)
        self.ch8disp = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ch8disp.setFont(font)
        self.ch8disp.setObjectName("ch8disp")
        self.gridLayout.addWidget(self.ch8disp, 8, 2, 1, 1)
        self.label_17 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 0, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 0, 2, 1, 1)
        self.ch1box = QtGui.QCheckBox(self.gridLayoutWidget)
        self.ch1box.setEnabled(False)
        self.ch1box.setChecked(True)
        self.ch1box.setObjectName("ch1box")
        self.gridLayout.addWidget(self.ch1box, 1, 0, 1, 1)
        self.DelayConfigWidget.addTab(self.counter_tab, "")
        self.action_tab = QtGui.QWidget()
        self.action_tab.setObjectName("action_tab")
        self.gridLayoutWidget_3 = QtGui.QWidget(self.action_tab)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(20, 20, 641, 31))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.rulesLayout = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.rulesLayout.setObjectName("rulesLayout")
        self.addButton = QtGui.QPushButton(self.action_tab)
        self.addButton.setGeometry(QtCore.QRect(120, 330, 75, 23))
        self.addButton.setObjectName("addButton")
        self.removeButton = QtGui.QPushButton(self.action_tab)
        self.removeButton.setGeometry(QtCore.QRect(510, 330, 75, 23))
        self.removeButton.setObjectName("removeButton")
        self.DelayConfigWidget.addTab(self.action_tab, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.label_21 = QtGui.QLabel(self.tab)
        self.label_21.setGeometry(QtCore.QRect(228, 58, 46, 13))
        self.label_21.setObjectName("label_21")
        self.IncreaseB_Button = QtGui.QPushButton(self.tab)
        self.IncreaseB_Button.setGeometry(QtCore.QRect(340, 100, 31, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.IncreaseB_Button.setFont(font)
        self.IncreaseB_Button.setObjectName("IncreaseB_Button")
        self.CoarseB_Entry = QtGui.QDoubleSpinBox(self.tab)
        self.CoarseB_Entry.setGeometry(QtCore.QRect(148, 73, 71, 22))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.CoarseB_Entry.setFont(font)
        self.CoarseB_Entry.setDecimals(3)
        self.CoarseB_Entry.setMaximum(4.0)
        self.CoarseB_Entry.setProperty("value", QtCore.QVariant(2.077))
        self.CoarseB_Entry.setObjectName("CoarseB_Entry")
        self.SetBField_Button = QtGui.QPushButton(self.tab)
        self.SetBField_Button.setGeometry(QtCore.QRect(78, 54, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.SetBField_Button.setFont(font)
        self.SetBField_Button.setObjectName("SetBField_Button")
        self.label_20 = QtGui.QLabel(self.tab)
        self.label_20.setGeometry(QtCore.QRect(148, 58, 46, 13))
        self.label_20.setObjectName("label_20")
        self.DecreaseB_Button = QtGui.QPushButton(self.tab)
        self.DecreaseB_Button.setGeometry(QtCore.QRect(300, 100, 31, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.DecreaseB_Button.setFont(font)
        self.DecreaseB_Button.setObjectName("DecreaseB_Button")
        self.FineBStepSize_Entry = QtGui.QDoubleSpinBox(self.tab)
        self.FineBStepSize_Entry.setGeometry(QtCore.QRect(300, 73, 71, 22))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.FineBStepSize_Entry.setFont(font)
        self.FineBStepSize_Entry.setDecimals(0)
        self.FineBStepSize_Entry.setMaximum(4096.0)
        self.FineBStepSize_Entry.setProperty("value", QtCore.QVariant(5.0))
        self.FineBStepSize_Entry.setObjectName("FineBStepSize_Entry")
        self.label_22 = QtGui.QLabel(self.tab)
        self.label_22.setGeometry(QtCore.QRect(307, 58, 81, 16))
        self.label_22.setObjectName("label_22")
        self.FineB_Entry = QtGui.QDoubleSpinBox(self.tab)
        self.FineB_Entry.setGeometry(QtCore.QRect(225, 73, 71, 22))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.FineB_Entry.setFont(font)
        self.FineB_Entry.setDecimals(0)
        self.FineB_Entry.setMaximum(4096.0)
        self.FineB_Entry.setProperty("value", QtCore.QVariant(2077.0))
        self.FineB_Entry.setObjectName("FineB_Entry")
        self.DelayConfigWidget.addTab(self.tab, "")
        self.delay_config_tab = QtGui.QWidget()
        self.delay_config_tab.setObjectName("delay_config_tab")
        self.expDelay = QtGui.QDoubleSpinBox(self.delay_config_tab)
        self.expDelay.setGeometry(QtCore.QRect(330, 40, 111, 22))
        self.expDelay.setMaximum(999999.99)
        self.expDelay.setObjectName("expDelay")
        self.label = QtGui.QLabel(self.delay_config_tab)
        self.label.setGeometry(QtCore.QRect(50, 40, 271, 16))
        self.label.setObjectName("label")
        self.DelayConfigWidget.addTab(self.delay_config_tab, "")
        CounterConfigWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(CounterConfigWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 798, 22))
        self.menubar.setObjectName("menubar")
        CounterConfigWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(CounterConfigWindow)
        self.statusbar.setObjectName("statusbar")
        CounterConfigWindow.setStatusBar(self.statusbar)

        self.retranslateUi(CounterConfigWindow)
        self.DelayConfigWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CounterConfigWindow)

    def retranslateUi(self, CounterConfigWindow):
        CounterConfigWindow.setWindowTitle(QtGui.QApplication.translate("CounterConfigWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.ch2box.setText(QtGui.QApplication.translate("CounterConfigWindow", "Counter 2", None, QtGui.QApplication.UnicodeUTF8))
        self.ch3box.setText(QtGui.QApplication.translate("CounterConfigWindow", "Counter 3", None, QtGui.QApplication.UnicodeUTF8))
        self.ch4box.setText(QtGui.QApplication.translate("CounterConfigWindow", "Counter 4", None, QtGui.QApplication.UnicodeUTF8))
        self.ch5box.setText(QtGui.QApplication.translate("CounterConfigWindow", "Counter 5", None, QtGui.QApplication.UnicodeUTF8))
        self.ch6box.setText(QtGui.QApplication.translate("CounterConfigWindow", "Counter 6", None, QtGui.QApplication.UnicodeUTF8))
        self.ch7box.setText(QtGui.QApplication.translate("CounterConfigWindow", "Counter 7", None, QtGui.QApplication.UnicodeUTF8))
        self.ch8box.setText(QtGui.QApplication.translate("CounterConfigWindow", "Counter 8", None, QtGui.QApplication.UnicodeUTF8))
        self.ch1av.setText(QtGui.QApplication.translate("CounterConfigWindow", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.ch2av.setText(QtGui.QApplication.translate("CounterConfigWindow", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.ch3av.setText(QtGui.QApplication.translate("CounterConfigWindow", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.ch4av.setText(QtGui.QApplication.translate("CounterConfigWindow", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.ch5av.setText(QtGui.QApplication.translate("CounterConfigWindow", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.ch6av.setText(QtGui.QApplication.translate("CounterConfigWindow", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.ch7av.setText(QtGui.QApplication.translate("CounterConfigWindow", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.ch8av.setText(QtGui.QApplication.translate("CounterConfigWindow", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.ch1disp.setText(QtGui.QApplication.translate("CounterConfigWindow", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.ch2disp.setText(QtGui.QApplication.translate("CounterConfigWindow", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.ch3disp.setText(QtGui.QApplication.translate("CounterConfigWindow", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.ch4disp.setText(QtGui.QApplication.translate("CounterConfigWindow", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.ch5disp.setText(QtGui.QApplication.translate("CounterConfigWindow", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.ch6disp.setText(QtGui.QApplication.translate("CounterConfigWindow", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.ch7disp.setText(QtGui.QApplication.translate("CounterConfigWindow", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.ch8disp.setText(QtGui.QApplication.translate("CounterConfigWindow", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("CounterConfigWindow", "Average", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("CounterConfigWindow", "Above threshold", None, QtGui.QApplication.UnicodeUTF8))
        self.ch1box.setText(QtGui.QApplication.translate("CounterConfigWindow", "Counter 1", None, QtGui.QApplication.UnicodeUTF8))
        self.DelayConfigWidget.setTabText(self.DelayConfigWidget.indexOf(self.counter_tab), QtGui.QApplication.translate("CounterConfigWindow", "Counters", None, QtGui.QApplication.UnicodeUTF8))
        self.addButton.setText(QtGui.QApplication.translate("CounterConfigWindow", "Add rule", None, QtGui.QApplication.UnicodeUTF8))
        self.removeButton.setText(QtGui.QApplication.translate("CounterConfigWindow", "Remove rule", None, QtGui.QApplication.UnicodeUTF8))
        self.DelayConfigWidget.setTabText(self.DelayConfigWidget.indexOf(self.action_tab), QtGui.QApplication.translate("CounterConfigWindow", "Actions", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("CounterConfigWindow", "Fine", None, QtGui.QApplication.UnicodeUTF8))
        self.IncreaseB_Button.setText(QtGui.QApplication.translate("CounterConfigWindow", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.SetBField_Button.setText(QtGui.QApplication.translate("CounterConfigWindow", "Set B \n"
"Field", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("CounterConfigWindow", "Coarse", None, QtGui.QApplication.UnicodeUTF8))
        self.DecreaseB_Button.setText(QtGui.QApplication.translate("CounterConfigWindow", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("CounterConfigWindow", "Fine Step Size", None, QtGui.QApplication.UnicodeUTF8))
        self.DelayConfigWidget.setTabText(self.DelayConfigWidget.indexOf(self.tab), QtGui.QApplication.translate("CounterConfigWindow", "B Field Control", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("CounterConfigWindow", "Delay between the experimental pionts, (milliseconds)", None, QtGui.QApplication.UnicodeUTF8))
        self.DelayConfigWidget.setTabText(self.DelayConfigWidget.indexOf(self.delay_config_tab), QtGui.QApplication.translate("CounterConfigWindow", "Experiment Delay", None, QtGui.QApplication.UnicodeUTF8))

