# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'iodineeomgui.ui'
#
# Created: Mon Apr 07 10:51:24 2014
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_IodineCellEOM(object):
    def setupUi(self, IodineCellEOM):
        IodineCellEOM.setObjectName(_fromUtf8("IodineCellEOM"))
        IodineCellEOM.resize(312, 118)
        self.pushButton = QtGui.QPushButton(IodineCellEOM)
        self.pushButton.setGeometry(QtCore.QRect(10, 82, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(IodineCellEOM)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 82, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(IodineCellEOM)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 41, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.pushButton_4 = QtGui.QPushButton(IodineCellEOM)
        self.pushButton_4.setGeometry(QtCore.QRect(60, 41, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.lcdNumber = QtGui.QLCDNumber(IodineCellEOM)
        self.lcdNumber.setGeometry(QtCore.QRect(120, 21, 141, 51))
        self.lcdNumber.setNumDigits(5)
        self.lcdNumber.setProperty(_fromUtf8("intValue"), 10262)
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.label = QtGui.QLabel(IodineCellEOM)
        self.label.setGeometry(QtCore.QRect(260, 51, 46, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.checkBox = QtGui.QCheckBox(IodineCellEOM)
        self.checkBox.setGeometry(QtCore.QRect(170, 1, 91, 17))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 153, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.checkBox.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox.setFont(font)
        self.checkBox.setCheckable(True)
        self.checkBox.setChecked(False)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.manual_entry = QtGui.QDoubleSpinBox(IodineCellEOM)
        self.manual_entry.setGeometry(QtCore.QRect(8, 11, 71, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.manual_entry.setFont(font)
        self.manual_entry.setDecimals(0)
        self.manual_entry.setMinimum(10000.0)
        self.manual_entry.setMaximum(10500.0)
        self.manual_entry.setProperty(_fromUtf8("value"), 10262.0)
        self.manual_entry.setObjectName(_fromUtf8("manual_entry"))
        self.pushButton_5 = QtGui.QPushButton(IodineCellEOM)
        self.pushButton_5.setGeometry(QtCore.QRect(81, 10, 31, 23))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))

        self.retranslateUi(IodineCellEOM)
        QtCore.QMetaObject.connectSlotsByName(IodineCellEOM)

    def retranslateUi(self, IodineCellEOM):
        IodineCellEOM.setWindowTitle(QtGui.QApplication.translate("IodineCellEOM", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("IodineCellEOM", "10262 MHz", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("IodineCellEOM", "10272 MHz", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("IodineCellEOM", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("IodineCellEOM", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("IodineCellEOM", "MHz", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("IodineCellEOM", "PLL Locked?", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setText(QtGui.QApplication.translate("IodineCellEOM", "GO", None, QtGui.QApplication.UnicodeUTF8))

