# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainion_2.ui'
#
# Created: Tue Dec 13 21:12:33 2016
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1048, 560)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 0, 731, 511))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.scanTab = QtGui.QWidget()
        self.scanTab.setStyleSheet("background-color: rgb(166, 255, 253);")
        self.scanTab.setObjectName("scanTab")
        self.progressBar = QtGui.QProgressBar(self.scanTab)
        self.progressBar.setGeometry(QtCore.QRect(40, 370, 651, 23))
        self.progressBar.setMaximum(5)
        self.progressBar.setProperty("value", QtCore.QVariant(0))
        self.progressBar.setObjectName("progressBar")
        self.simple_scan_qwt_plot = Qwt5.QwtPlot(self.scanTab)
        self.simple_scan_qwt_plot.setGeometry(QtCore.QRect(30, 30, 651, 321))
        self.simple_scan_qwt_plot.setObjectName("simple_scan_qwt_plot")
        self.reset_scan_Button = QtGui.QPushButton(self.scanTab)
        self.reset_scan_Button.setGeometry(QtCore.QRect(40, 420, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.reset_scan_Button.setFont(font)
        self.reset_scan_Button.setObjectName("reset_scan_Button")
        self.averageNumber = QtGui.QLCDNumber(self.scanTab)
        self.averageNumber.setGeometry(QtCore.QRect(520, 410, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.averageNumber.setFont(font)
        self.averageNumber.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.averageNumber.setSmallDecimalPoint(False)
        self.averageNumber.setNumDigits(6)
        self.averageNumber.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.averageNumber.setProperty("value", QtCore.QVariant(0.0))
        self.averageNumber.setObjectName("averageNumber")
        self.label_19 = QtGui.QLabel(self.scanTab)
        self.label_19.setGeometry(QtCore.QRect(390, 410, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.scan_num_exp_label = QtGui.QLabel(self.scanTab)
        self.scan_num_exp_label.setGeometry(QtCore.QRect(360, 430, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.scan_num_exp_label.setFont(font)
        self.scan_num_exp_label.setObjectName("scan_num_exp_label")
        self.tabWidget.addTab(self.scanTab, "")
        self.freqScan = QtGui.QWidget()
        self.freqScan.setStyleSheet("background-color: rgb(185, 255, 164);")
        self.freqScan.setObjectName("freqScan")
        self.freq_scan_qwt_plot = Qwt5.QwtPlot(self.freqScan)
        self.freq_scan_qwt_plot.setGeometry(QtCore.QRect(30, 20, 661, 351))
        self.freq_scan_qwt_plot.setObjectName("freq_scan_qwt_plot")
        self.freq_description = QtGui.QLabel(self.freqScan)
        self.freq_description.setGeometry(QtCore.QRect(150, 440, 371, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.freq_description.setFont(font)
        self.freq_description.setObjectName("freq_description")
        self.freq_stop = QtGui.QDoubleSpinBox(self.freqScan)
        self.freq_stop.setGeometry(QtCore.QRect(413, 418, 101, 20))
        self.freq_stop.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.freq_stop.setDecimals(6)
        self.freq_stop.setMinimum(0.1)
        self.freq_stop.setMaximum(9999999.99)
        self.freq_stop.setProperty("value", QtCore.QVariant(1.01))
        self.freq_stop.setObjectName("freq_stop")
        self.freq_step = QtGui.QDoubleSpinBox(self.freqScan)
        self.freq_step.setGeometry(QtCore.QRect(516, 418, 91, 20))
        self.freq_step.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.freq_step.setDecimals(6)
        self.freq_step.setMinimum(-999999.999)
        self.freq_step.setMaximum(999999.999)
        self.freq_step.setSingleStep(0.001)
        self.freq_step.setProperty("value", QtCore.QVariant(0.001))
        self.freq_step.setObjectName("freq_step")
        self.freq_start = QtGui.QDoubleSpinBox(self.freqScan)
        self.freq_start.setGeometry(QtCore.QRect(311, 418, 101, 20))
        self.freq_start.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.freq_start.setDecimals(6)
        self.freq_start.setMinimum(0.1)
        self.freq_start.setMaximum(999999.99)
        self.freq_start.setObjectName("freq_start")
        self.label_13 = QtGui.QLabel(self.freqScan)
        self.label_13.setGeometry(QtCore.QRect(318, 380, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtGui.QLabel(self.freqScan)
        self.label_14.setGeometry(QtCore.QRect(430, 380, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtGui.QLabel(self.freqScan)
        self.label_15.setGeometry(QtCore.QRect(540, 380, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.freq_current = QtGui.QLabel(self.freqScan)
        self.freq_current.setGeometry(QtCore.QRect(610, 460, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.freq_current.setFont(font)
        self.freq_current.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.freq_current.setObjectName("freq_current")
        self.freq_device = QtGui.QComboBox(self.freqScan)
        self.freq_device.setGeometry(QtCore.QRect(28, 418, 121, 21))
        self.freq_device.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.freq_device.setObjectName("freq_device")
        self.label_12 = QtGui.QLabel(self.freqScan)
        self.label_12.setGeometry(QtCore.QRect(630, 380, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.freq_default = QtGui.QDoubleSpinBox(self.freqScan)
        self.freq_default.setGeometry(QtCore.QRect(610, 418, 101, 20))
        self.freq_default.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.freq_default.setDecimals(6)
        self.freq_default.setMinimum(0.02)
        self.freq_default.setMaximum(999999.99)
        self.freq_default.setSingleStep(1.0)
        self.freq_default.setObjectName("freq_default")
        self.label_17 = QtGui.QLabel(self.freqScan)
        self.label_17.setGeometry(QtCore.QRect(20, 440, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_10 = QtGui.QLabel(self.freqScan)
        self.label_10.setGeometry(QtCore.QRect(30, 373, 51, 28))
        self.label_10.setMinimumSize(QtCore.QSize(0, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_18 = QtGui.QLabel(self.freqScan)
        self.label_18.setGeometry(QtCore.QRect(150, 379, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.freq_property = QtGui.QComboBox(self.freqScan)
        self.freq_property.setGeometry(QtCore.QRect(148, 418, 161, 21))
        self.freq_property.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.freq_property.setObjectName("freq_property")
        self.freq_device_2 = QtGui.QComboBox(self.freqScan)
        self.freq_device_2.setGeometry(QtCore.QRect(28, 398, 121, 21))
        self.freq_device_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.freq_device_2.setObjectName("freq_device_2")
        self.label_16 = QtGui.QLabel(self.freqScan)
        self.label_16.setGeometry(QtCore.QRect(530, 440, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.freq_stop_2 = QtGui.QDoubleSpinBox(self.freqScan)
        self.freq_stop_2.setEnabled(False)
        self.freq_stop_2.setGeometry(QtCore.QRect(413, 398, 101, 20))
        self.freq_stop_2.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.freq_stop_2.setDecimals(6)
        self.freq_stop_2.setMinimum(0.1)
        self.freq_stop_2.setMaximum(9999999.99)
        self.freq_stop_2.setProperty("value", QtCore.QVariant(1.01))
        self.freq_stop_2.setObjectName("freq_stop_2")
        self.freq_step_2 = QtGui.QDoubleSpinBox(self.freqScan)
        self.freq_step_2.setGeometry(QtCore.QRect(516, 398, 91, 20))
        self.freq_step_2.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.freq_step_2.setDecimals(6)
        self.freq_step_2.setMinimum(-999999.999)
        self.freq_step_2.setMaximum(999999.999)
        self.freq_step_2.setSingleStep(0.001)
        self.freq_step_2.setProperty("value", QtCore.QVariant(0.001))
        self.freq_step_2.setObjectName("freq_step_2")
        self.freq_default_2 = QtGui.QDoubleSpinBox(self.freqScan)
        self.freq_default_2.setGeometry(QtCore.QRect(610, 398, 101, 20))
        self.freq_default_2.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.freq_default_2.setDecimals(6)
        self.freq_default_2.setMaximum(999999.99)
        self.freq_default_2.setSingleStep(1.0)
        self.freq_default_2.setObjectName("freq_default_2")
        self.freq_property_2 = QtGui.QComboBox(self.freqScan)
        self.freq_property_2.setGeometry(QtCore.QRect(148, 398, 161, 21))
        self.freq_property_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.freq_property_2.setObjectName("freq_property_2")
        self.freq_start_2 = QtGui.QDoubleSpinBox(self.freqScan)
        self.freq_start_2.setGeometry(QtCore.QRect(311, 398, 101, 20))
        self.freq_start_2.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.freq_start_2.setDecimals(6)
        self.freq_start_2.setMinimum(0.1)
        self.freq_start_2.setMaximum(999999.99)
        self.freq_start_2.setObjectName("freq_start_2")
        self.freq_checkBox_2 = QtGui.QCheckBox(self.freqScan)
        self.freq_checkBox_2.setEnabled(True)
        self.freq_checkBox_2.setGeometry(QtCore.QRect(6, 398, 20, 20))
        self.freq_checkBox_2.setObjectName("freq_checkBox_2")
        self.freq_current_2 = QtGui.QLabel(self.freqScan)
        self.freq_current_2.setGeometry(QtCore.QRect(610, 441, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.freq_current_2.setFont(font)
        self.freq_current_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.freq_current_2.setObjectName("freq_current_2")
        self.tabWidget.addTab(self.freqScan, "")
        self.timeScan = QtGui.QWidget()
        self.timeScan.setStyleSheet("background-color: rgb(255, 170, 255);")
        self.timeScan.setObjectName("timeScan")
        self.delay_scan_qwt_plot = Qwt5.QwtPlot(self.timeScan)
        self.delay_scan_qwt_plot.setGeometry(QtCore.QRect(40, 30, 641, 321))
        self.delay_scan_qwt_plot.setObjectName("delay_scan_qwt_plot")
        self.gridLayoutWidget_2 = QtGui.QWidget(self.timeScan)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(40, 370, 641, 61))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.delay_start = QtGui.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.delay_start.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.delay_start.setMinimum(0.1)
        self.delay_start.setMaximum(999999.99)
        self.delay_start.setObjectName("delay_start")
        self.gridLayout_2.addWidget(self.delay_start, 1, 2, 1, 1)
        self.delay_stop = QtGui.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.delay_stop.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.delay_stop.setMinimum(0.1)
        self.delay_stop.setMaximum(9999999.99)
        self.delay_stop.setProperty("value", QtCore.QVariant(10000.0))
        self.delay_stop.setObjectName("delay_stop")
        self.gridLayout_2.addWidget(self.delay_stop, 1, 3, 1, 1)
        self.delay_step = QtGui.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.delay_step.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.delay_step.setMinimum(0.02)
        self.delay_step.setMaximum(999999.99)
        self.delay_step.setSingleStep(1.0)
        self.delay_step.setProperty("value", QtCore.QVariant(20.0))
        self.delay_step.setObjectName("delay_step")
        self.gridLayout_2.addWidget(self.delay_step, 1, 4, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 3, 1, 1)
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 4, 1, 1)
        self.current_delay = QtGui.QLabel(self.gridLayoutWidget_2)
        self.current_delay.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.current_delay.setObjectName("current_delay")
        self.gridLayout_2.addWidget(self.current_delay, 1, 5, 1, 1)
        self.label_11 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 5, 1, 1)
        self.delay_chapter_line = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.delay_chapter_line.setEnabled(True)
        self.delay_chapter_line.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.delay_chapter_line.setReadOnly(True)
        self.delay_chapter_line.setObjectName("delay_chapter_line")
        self.gridLayout_2.addWidget(self.delay_chapter_line, 1, 0, 1, 1)
        self.delay_line_number = QtGui.QLabel(self.gridLayoutWidget_2)
        self.delay_line_number.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.delay_line_number.setObjectName("delay_line_number")
        self.gridLayout_2.addWidget(self.delay_line_number, 1, 1, 1, 1)
        self.tabWidget.addTab(self.timeScan, "")
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(760, 100, 71, 16))
        self.label_3.setObjectName("label_3")
        self.lcdNumber = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(910, 393, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber.setObjectName("lcdNumber")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(800, 400, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(760, 320, 151, 74))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.thresholdBox = QtGui.QSpinBox(self.gridLayoutWidget)
        self.thresholdBox.setProperty("value", QtCore.QVariant(2))
        self.thresholdBox.setObjectName("thresholdBox")
        self.gridLayout.addWidget(self.thresholdBox, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.repetitionBox = QtGui.QSpinBox(self.gridLayoutWidget)
        self.repetitionBox.setMinimum(1)
        self.repetitionBox.setMaximum(10000)
        self.repetitionBox.setProperty("value", QtCore.QVariant(100))
        self.repetitionBox.setObjectName("repetitionBox")
        self.gridLayout.addWidget(self.repetitionBox, 0, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 2, 0, 1, 1)
        self.ionnumberBox = QtGui.QSpinBox(self.gridLayoutWidget)
        self.ionnumberBox.setEnabled(False)
        self.ionnumberBox.setProperty("value", QtCore.QVariant(1))
        self.ionnumberBox.setObjectName("ionnumberBox")
        self.gridLayout.addWidget(self.ionnumberBox, 2, 1, 1, 1)
        self.histrogram_qwt_plot = Qwt5.QwtPlot(self.centralwidget)
        self.histrogram_qwt_plot.setGeometry(QtCore.QRect(760, 120, 271, 191))
        self.histrogram_qwt_plot.setObjectName("histrogram_qwt_plot")
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(760, 440, 261, 70))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_4 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.scan_Button = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.scan_Button.setFont(font)
        self.scan_Button.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.scan_Button.setCheckable(True)
        self.scan_Button.setObjectName("scan_Button")
        self.gridLayout_4.addWidget(self.scan_Button, 0, 0, 1, 1)
        self.scan_once = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.scan_once.setFont(font)
        self.scan_once.setChecked(True)
        self.scan_once.setObjectName("scan_once")
        self.gridLayout_4.addWidget(self.scan_once, 1, 0, 1, 1)
        self.pause_Button = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pause_Button.setFont(font)
        self.pause_Button.setCheckable(True)
        self.pause_Button.setObjectName("pause_Button")
        self.gridLayout_4.addWidget(self.pause_Button, 0, 1, 1, 1)
        self.resume_Button = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.resume_Button.setFont(font)
        self.resume_Button.setCheckable(True)
        self.resume_Button.setObjectName("resume_Button")
        self.gridLayout_4.addWidget(self.resume_Button, 1, 1, 1, 1)
        self.gridLayoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(772, 30, 271, 71))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setHorizontalSpacing(1)
        self.gridLayout_3.setVerticalSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.crystallize_button0 = QtGui.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.crystallize_button0.setFont(font)
        self.crystallize_button0.setObjectName("crystallize_button0")
        self.gridLayout_3.addWidget(self.crystallize_button0, 0, 0, 1, 1)
        self.crystallize_doubleSpinBox1 = QtGui.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.crystallize_doubleSpinBox1.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.crystallize_doubleSpinBox1.setDecimals(2)
        self.crystallize_doubleSpinBox1.setMaximum(999999.99)
        self.crystallize_doubleSpinBox1.setProperty("value", QtCore.QVariant(65.0))
        self.crystallize_doubleSpinBox1.setObjectName("crystallize_doubleSpinBox1")
        self.gridLayout_3.addWidget(self.crystallize_doubleSpinBox1, 2, 1, 1, 1)
        self.crystallize_button1 = QtGui.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.crystallize_button1.setFont(font)
        self.crystallize_button1.setObjectName("crystallize_button1")
        self.gridLayout_3.addWidget(self.crystallize_button1, 2, 0, 1, 1)
        self.crystallize_doubleSpinBox0 = QtGui.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.crystallize_doubleSpinBox0.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.crystallize_doubleSpinBox0.setMaximum(999999.99)
        self.crystallize_doubleSpinBox0.setProperty("value", QtCore.QVariant(155.0))
        self.crystallize_doubleSpinBox0.setObjectName("crystallize_doubleSpinBox0")
        self.gridLayout_3.addWidget(self.crystallize_doubleSpinBox0, 0, 1, 1, 1)
        self.apply_threshold = QtGui.QCheckBox(self.centralwidget)
        self.apply_threshold.setGeometry(QtCore.QRect(920, 320, 110, 40))
        self.apply_threshold.setObjectName("apply_threshold")
        self.Lower_Trap_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.Lower_Trap_checkBox.setGeometry(QtCore.QRect(780, 10, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Lower_Trap_checkBox.setFont(font)
        self.Lower_Trap_checkBox.setObjectName("Lower_Trap_checkBox")
        self.scan_method = QtGui.QComboBox(self.centralwidget)
        self.scan_method.setGeometry(QtCore.QRect(920, 0, 126, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.scan_method.setFont(font)
        self.scan_method.setObjectName("scan_method")
        self.TrigCam_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.TrigCam_checkBox.setGeometry(QtCore.QRect(920, 360, 110, 30))
        self.TrigCam_checkBox.setObjectName("TrigCam_checkBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1048, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuFit = QtGui.QMenu(self.menubar)
        self.menuFit.setObjectName("menuFit")
        self.menuPhase_Modulation = QtGui.QMenu(self.menubar)
        self.menuPhase_Modulation.setTearOffEnabled(False)
        self.menuPhase_Modulation.setObjectName("menuPhase_Modulation")
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuEOM = QtGui.QMenu(self.menubar)
        self.menuEOM.setObjectName("menuEOM")
        self.menuCAM = QtGui.QMenu(self.menubar)
        self.menuCAM.setObjectName("menuCAM")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSave = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.actionSave.setFont(font)
        self.actionSave.setObjectName("actionSave")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSave_Histogram = QtGui.QAction(MainWindow)
        self.actionSave_Histogram.setObjectName("actionSave_Histogram")
        self.actionFrequency_Fit = QtGui.QAction(MainWindow)
        self.actionFrequency_Fit.setObjectName("actionFrequency_Fit")
        self.actionSine_Fit = QtGui.QAction(MainWindow)
        self.actionSine_Fit.setObjectName("actionSine_Fit")
        self.actionControl_Window = QtGui.QAction(MainWindow)
        self.actionControl_Window.setObjectName("actionControl_Window")
        self.LoadSettings = QtGui.QAction(MainWindow)
        self.LoadSettings.setObjectName("LoadSettings")
        self.SaveSettings = QtGui.QAction(MainWindow)
        self.SaveSettings.setObjectName("SaveSettings")
        self.actionCounters = QtGui.QAction(MainWindow)
        self.actionCounters.setObjectName("actionCounters")
        self.actionRamsey_Fit = QtGui.QAction(MainWindow)
        self.actionRamsey_Fit.setObjectName("actionRamsey_Fit")
        self.actionCounters_Plot = QtGui.QAction(MainWindow)
        self.actionCounters_Plot.setObjectName("actionCounters_Plot")
        self.actionSet_Scan_File = QtGui.QAction(MainWindow)
        self.actionSet_Scan_File.setObjectName("actionSet_Scan_File")
        self.actionEOM_GUI = QtGui.QAction(MainWindow)
        self.actionEOM_GUI.setObjectName("actionEOM_GUI")
        self.actionOpenCam = QtGui.QAction(MainWindow)
        self.actionOpenCam.setObjectName("actionOpenCam")
        self.actionAnticrossing_Fit = QtGui.QAction(MainWindow)
        self.actionAnticrossing_Fit.setObjectName("actionAnticrossing_Fit")
        self.actionCoherent_Fit = QtGui.QAction(MainWindow)
        self.actionCoherent_Fit.setObjectName("actionCoherent_Fit")
        self.actionThermal_Fit = QtGui.QAction(MainWindow)
        self.actionThermal_Fit.setObjectName("actionThermal_Fit")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_Histogram)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuFit.addAction(self.actionFrequency_Fit)
        self.menuFit.addAction(self.actionAnticrossing_Fit)
        self.menuFit.addSeparator()
        self.menuFit.addAction(self.actionSine_Fit)
        self.menuFit.addAction(self.actionRamsey_Fit)
        self.menuFit.addAction(self.actionCoherent_Fit)
        self.menuFit.addAction(self.actionThermal_Fit)
        self.menuPhase_Modulation.addAction(self.actionControl_Window)
        self.menuSettings.addAction(self.LoadSettings)
        self.menuSettings.addAction(self.SaveSettings)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.actionCounters)
        self.menuSettings.addAction(self.actionCounters_Plot)
        self.menuSettings.addAction(self.actionSet_Scan_File)
        self.menuEOM.addAction(self.actionEOM_GUI)
        self.menuCAM.addAction(self.actionOpenCam)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuFit.menuAction())
        self.menubar.addAction(self.menuPhase_Modulation.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuEOM.menuAction())
        self.menubar.addAction(self.menuCAM.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.freq_checkBox_2)
        MainWindow.setTabOrder(self.freq_checkBox_2, self.freq_device_2)
        MainWindow.setTabOrder(self.freq_device_2, self.freq_property_2)
        MainWindow.setTabOrder(self.freq_property_2, self.freq_start_2)
        MainWindow.setTabOrder(self.freq_start_2, self.freq_stop_2)
        MainWindow.setTabOrder(self.freq_stop_2, self.freq_step_2)
        MainWindow.setTabOrder(self.freq_step_2, self.freq_default_2)
        MainWindow.setTabOrder(self.freq_default_2, self.freq_device)
        MainWindow.setTabOrder(self.freq_device, self.freq_property)
        MainWindow.setTabOrder(self.freq_property, self.freq_start)
        MainWindow.setTabOrder(self.freq_start, self.freq_stop)
        MainWindow.setTabOrder(self.freq_stop, self.freq_step)
        MainWindow.setTabOrder(self.freq_step, self.freq_default)
        MainWindow.setTabOrder(self.freq_default, self.Lower_Trap_checkBox)
        MainWindow.setTabOrder(self.Lower_Trap_checkBox, self.crystallize_button0)
        MainWindow.setTabOrder(self.crystallize_button0, self.crystallize_doubleSpinBox0)
        MainWindow.setTabOrder(self.crystallize_doubleSpinBox0, self.crystallize_button1)
        MainWindow.setTabOrder(self.crystallize_button1, self.crystallize_doubleSpinBox1)
        MainWindow.setTabOrder(self.crystallize_doubleSpinBox1, self.repetitionBox)
        MainWindow.setTabOrder(self.repetitionBox, self.thresholdBox)
        MainWindow.setTabOrder(self.thresholdBox, self.apply_threshold)
        MainWindow.setTabOrder(self.apply_threshold, self.scan_Button)
        MainWindow.setTabOrder(self.scan_Button, self.pause_Button)
        MainWindow.setTabOrder(self.pause_Button, self.scan_once)
        MainWindow.setTabOrder(self.scan_once, self.reset_scan_Button)
        MainWindow.setTabOrder(self.reset_scan_Button, self.delay_chapter_line)
        MainWindow.setTabOrder(self.delay_chapter_line, self.delay_start)
        MainWindow.setTabOrder(self.delay_start, self.delay_stop)
        MainWindow.setTabOrder(self.delay_stop, self.delay_step)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.reset_scan_Button.setText(QtGui.QApplication.translate("MainWindow", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Average value", None, QtGui.QApplication.UnicodeUTF8))
        self.scan_num_exp_label.setText(QtGui.QApplication.translate("MainWindow", "over 0 expeiments ", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.scanTab), QtGui.QApplication.translate("MainWindow", "Alignment Scan", None, QtGui.QApplication.UnicodeUTF8))
        self.freq_description.setText(QtGui.QApplication.translate("MainWindow", "Unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Start ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Stop ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Step", None, QtGui.QApplication.UnicodeUTF8))
        self.freq_current.setText(QtGui.QApplication.translate("MainWindow", "0.10", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Default ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Device", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Property", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Current", None, QtGui.QApplication.UnicodeUTF8))
        self.freq_current_2.setText(QtGui.QApplication.translate("MainWindow", "0.10", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.freqScan), QtGui.QApplication.translate("MainWindow", "Frequency Scan", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Chapter", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Line", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Start delay", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Stop delay", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Step", None, QtGui.QApplication.UnicodeUTF8))
        self.current_delay.setText(QtGui.QApplication.translate("MainWindow", "0.10", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Current delay", None, QtGui.QApplication.UnicodeUTF8))
        self.delay_line_number.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.timeScan), QtGui.QApplication.translate("MainWindow", "Delay Scan", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Histogram", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Current Value:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Threshold", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">No. of expts</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Number of ions", None, QtGui.QApplication.UnicodeUTF8))
        self.scan_Button.setText(QtGui.QApplication.translate("MainWindow", "Scan", None, QtGui.QApplication.UnicodeUTF8))
        self.scan_once.setText(QtGui.QApplication.translate("MainWindow", "Scan Once", None, QtGui.QApplication.UnicodeUTF8))
        self.pause_Button.setText(QtGui.QApplication.translate("MainWindow", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.resume_Button.setText(QtGui.QApplication.translate("MainWindow", "Resume", None, QtGui.QApplication.UnicodeUTF8))
        self.crystallize_button0.setText(QtGui.QApplication.translate("MainWindow", "Need to crystallize", None, QtGui.QApplication.UnicodeUTF8))
        self.crystallize_button0.setShortcut(QtGui.QApplication.translate("MainWindow", "F9", None, QtGui.QApplication.UnicodeUTF8))
        self.crystallize_button1.setText(QtGui.QApplication.translate("MainWindow", "Crystallized", None, QtGui.QApplication.UnicodeUTF8))
        self.crystallize_button1.setShortcut(QtGui.QApplication.translate("MainWindow", "F10", None, QtGui.QApplication.UnicodeUTF8))
        self.apply_threshold.setText(QtGui.QApplication.translate("MainWindow", "Apply Threshold", None, QtGui.QApplication.UnicodeUTF8))
        self.Lower_Trap_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Lower Trap", None, QtGui.QApplication.UnicodeUTF8))
        self.TrigCam_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Trigger camera", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFit.setTitle(QtGui.QApplication.translate("MainWindow", "Fit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPhase_Modulation.setTitle(QtGui.QApplication.translate("MainWindow", "Modulation", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSettings.setTitle(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEOM.setTitle(QtGui.QApplication.translate("MainWindow", "EOM", None, QtGui.QApplication.UnicodeUTF8))
        self.menuCAM.setTitle(QtGui.QApplication.translate("MainWindow", "CAM", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Histogram.setText(QtGui.QApplication.translate("MainWindow", "Save with Histogram", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Histogram.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFrequency_Fit.setText(QtGui.QApplication.translate("MainWindow", "Frequency Fit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSine_Fit.setText(QtGui.QApplication.translate("MainWindow", "Sine Fit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionControl_Window.setText(QtGui.QApplication.translate("MainWindow", "Control Window...", None, QtGui.QApplication.UnicodeUTF8))
        self.LoadSettings.setText(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.SaveSettings.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCounters.setText(QtGui.QApplication.translate("MainWindow", "Counters", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRamsey_Fit.setText(QtGui.QApplication.translate("MainWindow", "Ramsey Fit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCounters_Plot.setText(QtGui.QApplication.translate("MainWindow", "Counter Plots", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSet_Scan_File.setText(QtGui.QApplication.translate("MainWindow", "Set Scan File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEOM_GUI.setText(QtGui.QApplication.translate("MainWindow", "EOM GUI", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenCam.setText(QtGui.QApplication.translate("MainWindow", "Open...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAnticrossing_Fit.setText(QtGui.QApplication.translate("MainWindow", "Anticrossing Fit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCoherent_Fit.setText(QtGui.QApplication.translate("MainWindow", "Coherent Fit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionThermal_Fit.setText(QtGui.QApplication.translate("MainWindow", "Thermal Fit", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import Qwt5
